/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ExerciseDetailResponse,
  ExerciseFiltersResponse,
  ExerciseListResponse,
  HTTPValidationError,
  ListExercisesExercisesGetParams
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type listExercisesExercisesGetResponse200 = {
  data: ExerciseListResponse
  status: 200
}

export type listExercisesExercisesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExercisesExercisesGetResponseSuccess = (listExercisesExercisesGetResponse200) & {
  headers: Headers;
};
export type listExercisesExercisesGetResponseError = (listExercisesExercisesGetResponse422) & {
  headers: Headers;
};

export type listExercisesExercisesGetResponse = (listExercisesExercisesGetResponseSuccess | listExercisesExercisesGetResponseError)

export const getListExercisesExercisesGetUrl = (params?: ListExercisesExercisesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/exercises?${stringifiedParams}` : `/exercises`
}

/**
 * @summary List Exercises
 */
export const listExercisesExercisesGet = async (params?: ListExercisesExercisesGetParams, options?: RequestInit): Promise<listExercisesExercisesGetResponse> => {

  return apiMutator<listExercisesExercisesGetResponse>(getListExercisesExercisesGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getListExercisesExercisesGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listExercisesExercisesGet>>, TError,{params?: ListExercisesExercisesGetParams}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof listExercisesExercisesGet>>, TError,{params?: ListExercisesExercisesGetParams}, TContext> => {

const mutationKey = ['listExercisesExercisesGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listExercisesExercisesGet>>, {params?: ListExercisesExercisesGetParams}> = (props) => {
          const {params} = props ?? {};

          return  listExercisesExercisesGet(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListExercisesExercisesGetMutationResult = NonNullable<Awaited<ReturnType<typeof listExercisesExercisesGet>>>

    export type ListExercisesExercisesGetMutationError = HTTPValidationError

    /**
 * @summary List Exercises
 */
export const useListExercisesExercisesGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listExercisesExercisesGet>>, TError,{params?: ListExercisesExercisesGetParams}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listExercisesExercisesGet>>,
        TError,
        {params?: ListExercisesExercisesGetParams},
        TContext
      > => {
      return useMutation(getListExercisesExercisesGetMutationOptions(options), queryClient);
    }
    export type getExerciseFiltersExercisesFiltersGetResponse200 = {
  data: ExerciseFiltersResponse
  status: 200
}

export type getExerciseFiltersExercisesFiltersGetResponseSuccess = (getExerciseFiltersExercisesFiltersGetResponse200) & {
  headers: Headers;
};
;

export type getExerciseFiltersExercisesFiltersGetResponse = (getExerciseFiltersExercisesFiltersGetResponseSuccess)

export const getGetExerciseFiltersExercisesFiltersGetUrl = () => {




  return `/exercises/filters`
}

/**
 * @summary Get Exercise Filters
 */
export const getExerciseFiltersExercisesFiltersGet = async ( options?: RequestInit): Promise<getExerciseFiltersExercisesFiltersGetResponse> => {

  return apiMutator<getExerciseFiltersExercisesFiltersGetResponse>(getGetExerciseFiltersExercisesFiltersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExerciseFiltersExercisesFiltersGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>, TError,void, TContext> => {

const mutationKey = ['getExerciseFiltersExercisesFiltersGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>, void> = () => {


          return  getExerciseFiltersExercisesFiltersGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetExerciseFiltersExercisesFiltersGetMutationResult = NonNullable<Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>>

    export type GetExerciseFiltersExercisesFiltersGetMutationError = unknown

    /**
 * @summary Get Exercise Filters
 */
export const useGetExerciseFiltersExercisesFiltersGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getExerciseFiltersExercisesFiltersGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetExerciseFiltersExercisesFiltersGetMutationOptions(options), queryClient);
    }
    export type getExerciseExercisesExerciseIdGetResponse200 = {
  data: ExerciseDetailResponse
  status: 200
}

export type getExerciseExercisesExerciseIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseExercisesExerciseIdGetResponseSuccess = (getExerciseExercisesExerciseIdGetResponse200) & {
  headers: Headers;
};
export type getExerciseExercisesExerciseIdGetResponseError = (getExerciseExercisesExerciseIdGetResponse422) & {
  headers: Headers;
};

export type getExerciseExercisesExerciseIdGetResponse = (getExerciseExercisesExerciseIdGetResponseSuccess | getExerciseExercisesExerciseIdGetResponseError)

export const getGetExerciseExercisesExerciseIdGetUrl = (exerciseId: string,) => {




  return `/exercises/${exerciseId}`
}

/**
 * @summary Get Exercise
 */
export const getExerciseExercisesExerciseIdGet = async (exerciseId: string, options?: RequestInit): Promise<getExerciseExercisesExerciseIdGetResponse> => {

  return apiMutator<getExerciseExercisesExerciseIdGetResponse>(getGetExerciseExercisesExerciseIdGetUrl(exerciseId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExerciseExercisesExerciseIdGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>, TError,{exerciseId: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>, TError,{exerciseId: string}, TContext> => {

const mutationKey = ['getExerciseExercisesExerciseIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>, {exerciseId: string}> = (props) => {
          const {exerciseId} = props ?? {};

          return  getExerciseExercisesExerciseIdGet(exerciseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetExerciseExercisesExerciseIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>>

    export type GetExerciseExercisesExerciseIdGetMutationError = HTTPValidationError

    /**
 * @summary Get Exercise
 */
export const useGetExerciseExercisesExerciseIdGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>, TError,{exerciseId: string}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getExerciseExercisesExerciseIdGet>>,
        TError,
        {exerciseId: string},
        TContext
      > => {
      return useMutation(getGetExerciseExercisesExerciseIdGetMutationOptions(options), queryClient);
    }
