/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface AppSupportedValuesResponse {
  e1rm_formulas: string[];
  personal_record_types: string[];
  mesocycle_goals: string[];
}
