/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { ExerciseProgressPointResponse } from './exerciseProgressPointResponse';
import type { ProgressiveOverloadResponse } from './progressiveOverloadResponse';
import type { WeeklyVolumeProgressPointResponse } from './weeklyVolumeProgressPointResponse';
import type { WorkoutStreaksResponse } from './workoutStreaksResponse';

export interface ExerciseProgressResponse {
  exercise_id: string;
  exercise_name: string;
  default_formula: string;
  e1rm_history: ExerciseProgressPointResponse[];
  volume_history: ExerciseProgressPointResponse[];
  weekly_volume_history: WeeklyVolumeProgressPointResponse[];
  progressive_overload: ProgressiveOverloadResponse[];
  workout_streaks: WorkoutStreaksResponse;
}
