/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { E1RMFormulaResponse } from './e1RMFormulaResponse';

export interface ExerciseProgressPointResponse {
  session_id: number;
  performed_at: string;
  best_set_id: number | null;
  weight_kg: number | null;
  reps: number | null;
  default_e1rm: number | null;
  formulas: E1RMFormulaResponse;
  volume_load: number;
}
