/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface PersonalRecordResponse {
  id: number;
  user_id: number;
  exercise_id: string;
  record_type: string;
  value: number;
  achieved_on: string;
  session_id: number | null;
  set_id: number | null;
  notes: string | null;
  created_at: string;
}
