/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface TrainingBlockSummaryResponse {
  completed_sessions: number;
  total_sets: number;
  distinct_exercises: number;
  total_volume_load: number;
  average_session_volume_load: number;
  average_session_rpe: number | null;
}
