/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AppConfigResponse
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getAppConfigMetaAppConfigGetResponse200 = {
  data: AppConfigResponse
  status: 200
}

export type getAppConfigMetaAppConfigGetResponseSuccess = (getAppConfigMetaAppConfigGetResponse200) & {
  headers: Headers;
};
;

export type getAppConfigMetaAppConfigGetResponse = (getAppConfigMetaAppConfigGetResponseSuccess)

export const getGetAppConfigMetaAppConfigGetUrl = () => {




  return `/meta/app-config`
}

/**
 * @summary Get App Config
 */
export const getAppConfigMetaAppConfigGet = async ( options?: RequestInit): Promise<getAppConfigMetaAppConfigGetResponse> => {

  return apiMutator<getAppConfigMetaAppConfigGetResponse>(getGetAppConfigMetaAppConfigGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAppConfigMetaAppConfigGetQueryKey = () => {
    return [
    `/meta/app-config`
    ] as const;
    }


export const getGetAppConfigMetaAppConfigGetQueryOptions = <TData = Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAppConfigMetaAppConfigGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>> = ({ signal }) => getAppConfigMetaAppConfigGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAppConfigMetaAppConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>>
export type GetAppConfigMetaAppConfigGetQueryError = unknown


export function useGetAppConfigMetaAppConfigGet<TData = Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAppConfigMetaAppConfigGet<TData = Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>,
          TError,
          Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAppConfigMetaAppConfigGet<TData = Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get App Config
 */

export function useGetAppConfigMetaAppConfigGet<TData = Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAppConfigMetaAppConfigGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAppConfigMetaAppConfigGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






