import { tokens } from "./tokens";

const c = tokens.color;

export const darkTheme = {
  background: c.root,
  backgroundFocus: c.screen,
  surface: c.surface,
  surfaceHover: c.surfaceLight,
  surfaceActive: c.cardElevated,
  surface1: c.card,
  surface2: c.cardSoft,
  surface3: c.cardElevated,
  borderColor: c.border,
  borderColorHover: c.borderLight,
  borderColorFocus: c.accent,
  color: c.text,
  colorHover: c.text,
  colorPress: c.text,
  colorFocus: c.accent,
  colorMuted: c.muted,
  colorFaint: c.faint,
  colorAccent: c.accent,
  colorGreen: c.green,
  colorGreenDark: c.greenDark,
  colorRed: c.red,
  colorRedDark: c.redDark,
  colorGold: c.gold,
  colorOrange: c.orange,
  colorPurple: c.purple,
  colorPurpleDark: c.purpleDark,
  colorBlue: c.blue,
  colorBlueDark: c.blueDark,
  accent: c.accent,
  accentHover: c.coral,
  accentPress: c.accent,
  shadowColor: "#000000",
  shadowColorAccent: c.accent,
} as const;
