/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  ExerciseProgressResponse,
  GetExerciseProgressProgressExerciseIdGetParams,
  HTTPValidationError
} from '../../model';


export type getExerciseProgressProgressExerciseIdGetResponse200 = {
  data: ExerciseProgressResponse
  status: 200
}

export type getExerciseProgressProgressExerciseIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseProgressProgressExerciseIdGetResponseSuccess = (getExerciseProgressProgressExerciseIdGetResponse200) & {
  headers: Headers;
};
export type getExerciseProgressProgressExerciseIdGetResponseError = (getExerciseProgressProgressExerciseIdGetResponse422) & {
  headers: Headers;
};

export type getExerciseProgressProgressExerciseIdGetResponse = (getExerciseProgressProgressExerciseIdGetResponseSuccess | getExerciseProgressProgressExerciseIdGetResponseError)

export const getGetExerciseProgressProgressExerciseIdGetUrl = (exerciseId: string,
    params?: GetExerciseProgressProgressExerciseIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/progress/${exerciseId}?${stringifiedParams}` : `/progress/${exerciseId}`
}

/**
 * @summary Get Exercise Progress
 */
export const getExerciseProgressProgressExerciseIdGet = async (exerciseId: string,
    params?: GetExerciseProgressProgressExerciseIdGetParams, options?: RequestInit): Promise<getExerciseProgressProgressExerciseIdGetResponse> => {

  const res = await fetch(getGetExerciseProgressProgressExerciseIdGetUrl(exerciseId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getExerciseProgressProgressExerciseIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getExerciseProgressProgressExerciseIdGetResponse
}


