/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type rootGetResponse200 = {
  data: unknown
  status: 200
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
;

export type rootGetResponse = (rootGetResponseSuccess)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * @summary Root
 */
export const rootGet = async ( options?: RequestInit): Promise<rootGetResponse> => {

  return apiMutator<rootGetResponse>(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getRootGetQueryKey = () => {
    return [
    `/`
    ] as const;
    }


export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = unknown


export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type healthCheckHealthGetResponse200 = {
  data: unknown
  status: 200
}

export type healthCheckHealthGetResponseSuccess = (healthCheckHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckHealthGetResponse = (healthCheckHealthGetResponseSuccess)

export const getHealthCheckHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health Check
 */
export const healthCheckHealthGet = async ( options?: RequestInit): Promise<healthCheckHealthGetResponse> => {

  return apiMutator<healthCheckHealthGetResponse>(getHealthCheckHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthCheckHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckHealthGet>>> = ({ signal }) => healthCheckHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthCheckHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheckHealthGet>>>
export type HealthCheckHealthGetQueryError = unknown


export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthCheckHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthCheckHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGet<TData = Awaited<ReturnType<typeof healthCheckHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthCheckHealthGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthCheckHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type dbTestDbTestGetResponse200 = {
  data: unknown
  status: 200
}

export type dbTestDbTestGetResponseSuccess = (dbTestDbTestGetResponse200) & {
  headers: Headers;
};
;

export type dbTestDbTestGetResponse = (dbTestDbTestGetResponseSuccess)

export const getDbTestDbTestGetUrl = () => {




  return `/db-test`
}

/**
 * Simple connectivity test endpoint used by tests.

Executes a lightweight statement and reports success or an error message.
 * @summary Db Test
 */
export const dbTestDbTestGet = async ( options?: RequestInit): Promise<dbTestDbTestGetResponse> => {

  return apiMutator<dbTestDbTestGetResponse>(getDbTestDbTestGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDbTestDbTestGetQueryKey = () => {
    return [
    `/db-test`
    ] as const;
    }


export const getDbTestDbTestGetQueryOptions = <TData = Awaited<ReturnType<typeof dbTestDbTestGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDbTestDbTestGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dbTestDbTestGet>>> = ({ signal }) => dbTestDbTestGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DbTestDbTestGetQueryResult = NonNullable<Awaited<ReturnType<typeof dbTestDbTestGet>>>
export type DbTestDbTestGetQueryError = unknown


export function useDbTestDbTestGet<TData = Awaited<ReturnType<typeof dbTestDbTestGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dbTestDbTestGet>>,
          TError,
          Awaited<ReturnType<typeof dbTestDbTestGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDbTestDbTestGet<TData = Awaited<ReturnType<typeof dbTestDbTestGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dbTestDbTestGet>>,
          TError,
          Awaited<ReturnType<typeof dbTestDbTestGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDbTestDbTestGet<TData = Awaited<ReturnType<typeof dbTestDbTestGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Db Test
 */

export function useDbTestDbTestGet<TData = Awaited<ReturnType<typeof dbTestDbTestGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbTestDbTestGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDbTestDbTestGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type testDbQueryDbQueryGetResponse200 = {
  data: unknown
  status: 200
}

export type testDbQueryDbQueryGetResponseSuccess = (testDbQueryDbQueryGetResponse200) & {
  headers: Headers;
};
;

export type testDbQueryDbQueryGetResponse = (testDbQueryDbQueryGetResponseSuccess)

export const getTestDbQueryDbQueryGetUrl = () => {




  return `/db-query`
}

/**
 * Run a small, dialect-aware query and return a human message.

For Postgres we attempt SELECT version(); for SQLite we call
sqlite_version() so tests using an in-memory SQLite DB succeed.
 * @summary Test Db Query
 */
export const testDbQueryDbQueryGet = async ( options?: RequestInit): Promise<testDbQueryDbQueryGetResponse> => {

  return apiMutator<testDbQueryDbQueryGetResponse>(getTestDbQueryDbQueryGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTestDbQueryDbQueryGetQueryKey = () => {
    return [
    `/db-query`
    ] as const;
    }


export const getTestDbQueryDbQueryGetQueryOptions = <TData = Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTestDbQueryDbQueryGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>> = ({ signal }) => testDbQueryDbQueryGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TestDbQueryDbQueryGetQueryResult = NonNullable<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>>
export type TestDbQueryDbQueryGetQueryError = unknown


export function useTestDbQueryDbQueryGet<TData = Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof testDbQueryDbQueryGet>>,
          TError,
          Awaited<ReturnType<typeof testDbQueryDbQueryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestDbQueryDbQueryGet<TData = Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof testDbQueryDbQueryGet>>,
          TError,
          Awaited<ReturnType<typeof testDbQueryDbQueryGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTestDbQueryDbQueryGet<TData = Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Test Db Query
 */

export function useTestDbQueryDbQueryGet<TData = Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof testDbQueryDbQueryGet>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTestDbQueryDbQueryGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






