/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export type rootGetResponse200 = {
  data: unknown
  status: 200
}

export type rootGetResponseSuccess = (rootGetResponse200) & {
  headers: Headers;
};
;

export type rootGetResponse = (rootGetResponseSuccess)

export const getRootGetUrl = () => {




  return `/`
}

/**
 * @summary Root
 */
export const rootGet = async ( options?: RequestInit): Promise<rootGetResponse> => {

  const res = await fetch(getRootGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rootGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rootGetResponse
}


export type healthCheckHealthGetResponse200 = {
  data: unknown
  status: 200
}

export type healthCheckHealthGetResponseSuccess = (healthCheckHealthGetResponse200) & {
  headers: Headers;
};
;

export type healthCheckHealthGetResponse = (healthCheckHealthGetResponseSuccess)

export const getHealthCheckHealthGetUrl = () => {




  return `/health`
}

/**
 * @summary Health Check
 */
export const healthCheckHealthGet = async ( options?: RequestInit): Promise<healthCheckHealthGetResponse> => {

  const res = await fetch(getHealthCheckHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthCheckHealthGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthCheckHealthGetResponse
}


export type dbTestDbTestGetResponse200 = {
  data: unknown
  status: 200
}

export type dbTestDbTestGetResponseSuccess = (dbTestDbTestGetResponse200) & {
  headers: Headers;
};
;

export type dbTestDbTestGetResponse = (dbTestDbTestGetResponseSuccess)

export const getDbTestDbTestGetUrl = () => {




  return `/db-test`
}

/**
 * Simple connectivity test endpoint used by tests.

Executes a lightweight statement and reports success or an error message.
 * @summary Db Test
 */
export const dbTestDbTestGet = async ( options?: RequestInit): Promise<dbTestDbTestGetResponse> => {

  const res = await fetch(getDbTestDbTestGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dbTestDbTestGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as dbTestDbTestGetResponse
}


export type testDbQueryDbQueryGetResponse200 = {
  data: unknown
  status: 200
}

export type testDbQueryDbQueryGetResponseSuccess = (testDbQueryDbQueryGetResponse200) & {
  headers: Headers;
};
;

export type testDbQueryDbQueryGetResponse = (testDbQueryDbQueryGetResponseSuccess)

export const getTestDbQueryDbQueryGetUrl = () => {




  return `/db-query`
}

/**
 * Run a small, dialect-aware query and return a human message.

For Postgres we attempt SELECT version(); for SQLite we call
sqlite_version() so tests using an in-memory SQLite DB succeed.
 * @summary Test Db Query
 */
export const testDbQueryDbQueryGet = async ( options?: RequestInit): Promise<testDbQueryDbQueryGetResponse> => {

  const res = await fetch(getTestDbQueryDbQueryGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: testDbQueryDbQueryGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as testDbQueryDbQueryGetResponse
}


