/**
 * Monolithic stylesheet — legacy.
 *
 * New styles should go in sub-modules:
 *   layoutStyles.ts   — screen, flex, row, layout patterns
 *   formStyles.ts     — inputs, buttons, form controls
 *   componentStyles.ts — cards, tags, progress bars, modals
 *
 * Only add to this file when migrating existing styles out.
 */

import { StyleSheet } from "react-native";

import { COLORS } from "./colors";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: COLORS.root, maxWidth: 390, width: "100%", alignSelf: "center" },
  screen: { flex: 1, backgroundColor: COLORS.screen },
  flexFill: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 28 },
  centeredContent: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 24, paddingBottom: 20 },
  headerRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
  headerTitle: { color: COLORS.text, fontSize: 17, fontWeight: "700" },
  headerSubtitle: { color: COLORS.muted, fontSize: 11, marginTop: 2 },
  roundButton: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.09)" },
  card: { backgroundColor: COLORS.card, borderWidth: 1, borderColor: COLORS.border, borderRadius: 24, paddingHorizontal: 16, paddingVertical: 16 },
  sectionEyebrow: { color: "rgba(255,255,255,0.35)", fontSize: 11, fontWeight: "700", letterSpacing: 1.4, textTransform: "uppercase" },
  primaryButton: { minHeight: 56, borderRadius: 18, backgroundColor: COLORS.teal, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 10 },
  primaryButtonText: { color: "#000000", fontSize: 15, fontWeight: "800" },
  oauthButton: { minHeight: 52, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.08)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 10 },
  oauthButtonText: { color: COLORS.text, fontSize: 14, fontWeight: "600" },
  tag: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4, alignSelf: "flex-start" },
  tagText: { fontSize: 10, fontWeight: "700" },
  progressTrack: { width: "100%", borderRadius: 999, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 999 },
  barRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-end" },
  barColumn: { flex: 1, alignItems: "center" },
  barTrackShell: { justifyContent: "flex-end", width: 26 },
  bar: { width: 22, borderRadius: 6, alignSelf: "center" },
  barLabel: { color: "rgba(255,255,255,0.3)", fontSize: 10, marginTop: 8 },
  chartArea: { position: "relative" },
  chartGridLine: { position: "absolute", left: 0, right: 0, height: 1, backgroundColor: "rgba(255,255,255,0.05)" },
  referenceLine: { position: "absolute", left: 0, right: 0, borderTopWidth: 1, borderStyle: "dashed", borderColor: "rgba(255,90,54,0.32)" },
  chartSegment: { position: "absolute", height: 2, borderRadius: 999 },
  chartDot: { position: "absolute", width: 8, height: 8, borderRadius: 4, borderWidth: 2 },
  chartLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: 8 },
  chartLabelText: { flex: 1, color: "rgba(255,255,255,0.3)", fontSize: 8, textAlign: "center" },
  splashLogo: { width: 96, height: 96, borderRadius: 28, backgroundColor: COLORS.teal, alignItems: "center", justifyContent: "center", ...{ shadowColor: COLORS.teal, shadowOpacity: 0.28, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8 } },
  splashTitle: { color: COLORS.text, fontSize: 32, fontWeight: "900", marginTop: 28 },
  splashSubtitle: { color: "rgba(255,255,255,0.35)", fontSize: 13, marginTop: 6 },
  splashProgressCard: { width: "100%", marginTop: 28, backgroundColor: "rgba(255,255,255,0.04)", borderWidth: 1, borderColor: COLORS.border, borderRadius: 22, paddingHorizontal: 18, paddingVertical: 20, gap: 12 },
  splashProgressValue: { color: COLORS.teal, fontSize: 24, fontWeight: "800", textAlign: "center" },
  splashStatus: { color: "rgba(255,255,255,0.35)", fontSize: 12, textAlign: "center" },
  splashFooter: { position: "absolute", bottom: 26, color: "rgba(255,255,255,0.2)", fontSize: 11 },
  authTop: { alignItems: "center", paddingTop: 20, paddingBottom: 28 },
  authLogo: { width: 72, height: 72, borderRadius: 22, backgroundColor: COLORS.teal, alignItems: "center", justifyContent: "center", ...{ shadowColor: COLORS.teal, shadowOpacity: 0.28, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8 } },
  authTitle: { color: COLORS.text, fontSize: 28, fontWeight: "900", marginTop: 22 },
  authSubtitle: { color: COLORS.muted, fontSize: 13, marginTop: 6 },
  formStack: { gap: 14 },
  fieldLabel: { color: "rgba(255,255,255,0.4)", fontSize: 11, fontWeight: "700", marginBottom: 8, letterSpacing: 0.4, textTransform: "uppercase" },
  inputWrap: { position: "relative" },
  input: { width: "100%", minHeight: 52, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: COLORS.text, paddingHorizontal: 16, fontSize: 14 },
  inputWithRight: { paddingRight: 46 },
  inputRightIcon: { position: "absolute", right: 14, top: 18 },
  linkText: { color: COLORS.teal, fontSize: 12, fontWeight: "600" },
  errorBox: { borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: "rgba(239,68,68,0.12)", borderWidth: 1, borderColor: "rgba(239,68,68,0.25)" },
  errorText: { color: COLORS.red, fontSize: 12 },
  fieldError: { color: COLORS.red, fontSize: 10, marginTop: 6, marginLeft: 2 },
  authDividerRow: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 26 },
  divider: { flex: 1, height: 1, backgroundColor: "rgba(255,255,255,0.08)" },
  dividerText: { color: "rgba(255,255,255,0.3)", fontSize: 11 },
  authBottomText: { color: COLORS.muted, fontSize: 13, textAlign: "center", marginTop: 24 },
  linkTextInline: { color: COLORS.teal, fontWeight: "700" },
  passwordChecks: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12 },
  passwordCheck: { flexDirection: "row", alignItems: "center", gap: 6 },
  checkBubble: { width: 14, height: 14, borderRadius: 7, backgroundColor: "rgba(255,255,255,0.1)", alignItems: "center", justifyContent: "center" },
  passwordCheckText: { color: "rgba(255,255,255,0.35)", fontSize: 10 },
  legalText: { color: "rgba(255,255,255,0.3)", fontSize: 11, lineHeight: 16 },
  mainHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingTop: 8 },
  homeIdentity: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatarBubble: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.teal, ...{ shadowColor: COLORS.teal, shadowOpacity: 0.28, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8 } },
  avatarInitials: { color: "#000000", fontSize: 14, fontWeight: "800" },
  kickerText: { color: "rgba(255,255,255,0.38)", fontSize: 10, textTransform: "uppercase", letterSpacing: 1.2 },
  greetingText: { color: COLORS.text, fontSize: 15, fontWeight: "700", marginTop: 2 },
  notificationDot: { position: "absolute", width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.teal, top: 9, right: 9 },
  inlineSection: { marginTop: 14 },
  bannerIcon: { width: 32, height: 32, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,90,54,0.2)" },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  rowGap: { flexDirection: "row", alignItems: "center", gap: 10 },
  rowGapTiny: { flexDirection: "row", alignItems: "center", gap: 4 },
  rowGapSmall: { flexDirection: "row", alignItems: "baseline", gap: 6 },
  rowGapLarge: { flexDirection: "row", alignItems: "center", gap: 10, flexWrap: "wrap" },
  smallStrongText: { color: COLORS.text, fontSize: 11, fontWeight: "700" },
  cardTitle: { color: COLORS.text, fontSize: 15, fontWeight: "800" },
  sectionCardTitle: { color: COLORS.text, fontSize: 13, fontWeight: "700" },
  statRowDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.06)", marginTop: 16, marginBottom: 16 },
  threeUp: { flexDirection: "row", alignItems: "stretch", justifyContent: "space-between" },
  statPill: { flex: 1, alignItems: "center", gap: 4 },
  statPillValue: { color: COLORS.text, fontSize: 15, fontWeight: "800" },
  statPillLabel: { color: "rgba(255,255,255,0.38)", fontSize: 10 },
  verticalDivider: { width: 1, backgroundColor: "rgba(255,255,255,0.07)", marginHorizontal: 8 },
  softIconWrap: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)" },
  detailLabel: { color: "rgba(255,255,255,0.4)", fontSize: 11, lineHeight: 16 },
  heroMetric: { color: COLORS.text, fontSize: 20, fontWeight: "800" },
  metricSuffix: { color: "rgba(255,255,255,0.4)", fontSize: 13 },
  metricChange: { fontSize: 11, fontWeight: "700" },
  sectionHeadingRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  metricBlockValue: { color: COLORS.text, fontSize: 14, fontWeight: "800" },
  metricBlockLabel: { color: "rgba(255,255,255,0.35)", fontSize: 9, marginTop: 3 },
  prCard: { width: 126, paddingHorizontal: 14, paddingVertical: 14 },
  prBadge: { fontSize: 9, fontWeight: "700", textTransform: "uppercase", letterSpacing: 1.1 },
  prValue: { fontSize: 16, fontWeight: "900", marginTop: 6 },
  tabIntro: { paddingTop: 8 },
  tabTitle: { color: COLORS.text, fontSize: 28, fontWeight: "900", marginTop: 4 },
  tabSubtitle: { color: COLORS.muted, fontSize: 12, marginTop: 4 },
  searchWrap: { flex: 1, minHeight: 50, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.09)", paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 10 },
  searchInput: { flex: 1, color: COLORS.text, fontSize: 13, paddingVertical: 0 },
  filterButton: { width: 48, height: 50, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.09)" },
  filterTagRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  activeFilterTag: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(255,90,54,0.15)", borderWidth: 1, borderColor: "rgba(255,90,54,0.3)" },
  activeFilterText: { color: COLORS.teal, fontSize: 11, fontWeight: "700" },
  resultsText: { color: "rgba(255,255,255,0.35)", fontSize: 11, marginBottom: 10 },
  listRowCard: { flexDirection: "row", alignItems: "center", gap: 10 },

  listRowBody: { flex: 1 },
  listRowTitle: { color: COLORS.text, fontSize: 13, fontWeight: "700" },
  emptyState: { alignItems: "center", paddingVertical: 40, gap: 8 },
  emptyStateTitle: { color: COLORS.text, fontSize: 15, fontWeight: "700" },
  emptyStateText: { color: COLORS.muted, fontSize: 13, textAlign: "center" },
  heroTitle: { color: COLORS.text, fontSize: 21, fontWeight: "900" },
  primaryMuscleTag: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(255,90,54,0.15)", borderWidth: 1, borderColor: "rgba(255,90,54,0.3)" },
  primaryMuscleDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.teal },
  primaryMuscleText: { color: COLORS.teal, fontSize: 12, fontWeight: "700" },
  secondaryMuscleTag: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.09)" },
  secondaryMuscleDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "rgba(255,255,255,0.4)" },
  secondaryMuscleText: { color: "rgba(255,255,255,0.62)", fontSize: 12 },
  stepRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  stepBubble: { width: 26, height: 26, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,90,54,0.2)" },
  stepBubbleText: { color: COLORS.teal, fontSize: 11, fontWeight: "800" },
  stepText: { flex: 1, color: "rgba(255,255,255,0.76)", fontSize: 13, lineHeight: 20 },
  tipRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  tipText: { flex: 1, color: "rgba(255,255,255,0.74)", fontSize: 13, lineHeight: 18 },
  trainHero: { borderRadius: 28, alignItems: "center", paddingHorizontal: 20, paddingVertical: 28, backgroundColor: COLORS.teal },
  trainHeroIcon: { width: 58, height: 58, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0,0,0,0.18)" },
  trainHeroTitle: { color: "#000000", fontSize: 18, fontWeight: "900", marginTop: 14 },
  trainHeroSubtitle: { color: "rgba(0,0,0,0.55)", fontSize: 12, marginTop: 4 },
  threeUpGrid: { flexDirection: "row", gap: 10 },
  twoUpGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  compactStatCard: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 82 },
  compactStatValue: { color: COLORS.text, fontSize: 18, fontWeight: "900" },
  compactStatLabel: { color: "rgba(255,255,255,0.35)", fontSize: 9, textAlign: "center", marginTop: 6 },
  sectionIconWrap: { width: 48, height: 48, borderRadius: 18, alignItems: "center", justifyContent: "center" },
  sectionIconWrapSmall: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  smallAccentButton: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: "rgba(255,90,54,0.15)", borderWidth: 1, borderColor: "rgba(255,90,54,0.3)" },
  smallAccentText: { color: COLORS.teal, fontSize: 12, fontWeight: "700" },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  smallActionTag: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, borderWidth: 1 },
  smallActionText: { fontSize: 12, fontWeight: "700" },
  dashedAddCard: { borderRadius: 24, borderWidth: 1, borderStyle: "dashed", borderColor: "rgba(255,255,255,0.12)", backgroundColor: "rgba(255,255,255,0.02)", paddingHorizontal: 16, paddingVertical: 16, flexDirection: "row", alignItems: "center", gap: 12 },
  addCircle: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.06)" },
  builderTopBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.06)" },
  saveChip: { minHeight: 34, borderRadius: 12, backgroundColor: COLORS.teal, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 },
  saveChipText: { color: "#000000", fontSize: 12, fontWeight: "800" },
  templateNameInput: { marginTop: 16, minHeight: 58, borderRadius: 18, fontSize: 16, fontWeight: "700" },
  stepperBtn: { width: 28, height: 28, borderRadius: 8, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  restChip: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", backgroundColor: "rgba(255,255,255,0.04)" },
  restChipText: { color: "rgba(255,255,255,0.6)", fontSize: 13, fontWeight: "600" },
  miniInput: { flex: 1, minWidth: 0, minHeight: 38, borderRadius: 10, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: COLORS.text, textAlign: "center", fontSize: 13, paddingHorizontal: 4 },
  gridHeaderText: { flex: 1, color: "rgba(255,255,255,0.3)", fontSize: 10, fontWeight: "700", textTransform: "uppercase", textAlign: "center", paddingHorizontal: 4 },
  dashedButton: { marginTop: 10, minHeight: 42, borderRadius: 14, borderWidth: 1, borderStyle: "dashed", borderColor: "rgba(255,90,54,0.25)", backgroundColor: "rgba(255,90,54,0.08)", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 6 },
  dashedButtonText: { color: COLORS.teal, fontSize: 12, fontWeight: "700" },
  selectableRow: { minHeight: 54, borderRadius: 14, borderWidth: 1, borderColor: COLORS.border, backgroundColor: "rgba(255,255,255,0.03)", justifyContent: "center", paddingHorizontal: 14 },
  chipButton: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", backgroundColor: "rgba(255,255,255,0.04)" },
  chipButtonText: { color: "rgba(255,255,255,0.5)", fontSize: 12, fontWeight: "600" },
  radioOuter: { width: 16, height: 16, borderRadius: 8, borderWidth: 2, alignItems: "center", justifyContent: "center" },
  radioInner: { width: 8, height: 8, borderRadius: 4 },
  stickyCard: { marginTop: 0, borderRadius: 0, marginHorizontal: -20, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14, borderLeftWidth: 0, borderRightWidth: 0, borderTopWidth: 0 },
  dangerPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: "rgba(239,68,68,0.12)", borderWidth: 1, borderColor: "rgba(239,68,68,0.25)" },
  dangerPillText: { color: COLORS.red, fontSize: 12, fontWeight: "600" },
  finishPill: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: COLORS.teal },
  finishPillText: { color: "#000000", fontSize: 12, fontWeight: "800" },
  timerText: { color: COLORS.text, fontSize: 18, fontWeight: "900" },
  timerSubtext: { color: "rgba(255,255,255,0.35)", fontSize: 10, marginTop: 2 },
  workoutGridHeader: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 4, marginBottom: 10 },
  workoutGridRow: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 4 },
  workoutGridIndex: { width: 32, alignItems: "center", justifyContent: "center" },
  doneToggle: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)" },
  moodButton: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "transparent" },
  notesInput: { flex: 1, minHeight: 64, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.04)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", color: COLORS.text, paddingHorizontal: 14, paddingVertical: 12, fontSize: 13, textAlignVertical: "top" },
  modalScrim: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.72)" },
  modalBackdrop: { flex: 1 },
  bottomSheet: { backgroundColor: "#111d1b", borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingHorizontal: 24, paddingTop: 14, paddingBottom: 26 },
  sheetHandle: { width: 40, height: 4, borderRadius: 4, alignSelf: "center", backgroundColor: "rgba(255,255,255,0.2)", marginBottom: 18 },
  sheetTitle: { color: COLORS.text, fontSize: 22, fontWeight: "900", textAlign: "center" },
  sheetSubtitle: { color: COLORS.muted, fontSize: 13, textAlign: "center", marginTop: 6 },
  historyMoodWrap: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.07)" },
  menuModalBackdrop: { flex: 1, justifyContent: "flex-start", alignItems: "flex-end", paddingTop: 60, paddingRight: 20 },
  menuModalContent: { width: 170, borderRadius: 18, backgroundColor: "#111d1b", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingVertical: 6 },
  confirmBackdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.6)", alignItems: "center", justifyContent: "center", paddingHorizontal: 24 },
  confirmDialog: { width: "100%", maxWidth: 320, borderRadius: 20, backgroundColor: "#111d1b", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", padding: 20, gap: 12 },
  confirmTitle: { color: COLORS.text, fontSize: 17, fontWeight: "700", textAlign: "center" },
  confirmMessage: { color: COLORS.muted, fontSize: 14, textAlign: "center", lineHeight: 20 },
  confirmButtons: { flexDirection: "row", gap: 10, marginTop: 4 },
  confirmButtonCancel: { flex: 1, minHeight: 44, borderRadius: 12, backgroundColor: "rgba(255,255,255,0.08)", alignItems: "center", justifyContent: "center" },
  confirmButtonConfirm: { flex: 1, minHeight: 44, borderRadius: 12, backgroundColor: COLORS.teal, alignItems: "center", justifyContent: "center" },
  confirmButtonText: { fontSize: 15, fontWeight: "700", color: COLORS.text },
  menuPopoverScreen: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0, zIndex: 100 },
  menuBackdrop: { flex: 1 },
  menuPopoverContent: { position: "absolute", top: 56, right: 20, width: 170, borderRadius: 18, backgroundColor: "#111d1b", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingVertical: 6 },
  menuPopover: { position: "absolute", top: 46, right: 0, width: 170, borderRadius: 18, backgroundColor: "#111d1b", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", paddingVertical: 6, zIndex: 100 },
  menuItem: { flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 14, paddingVertical: 12 },
  menuItemText: { color: "rgba(255,255,255,0.75)", fontSize: 13 },
  exerciseHeader: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.06)" },
  sessionGridHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 },
  sessionGridRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sessionCell: { flex: 1, minHeight: 34, borderRadius: 10, backgroundColor: "rgba(255,255,255,0.06)", alignItems: "center", justifyContent: "center" },
  sessionCellText: { color: COLORS.text, fontSize: 12, fontWeight: "700" },
  analyticsCard: { width: "48%", borderRadius: 16, backgroundColor: "rgba(139,92,246,0.1)", borderWidth: 1, borderColor: "rgba(139,92,246,0.15)", paddingHorizontal: 12, paddingVertical: 12 },
  analyticsLabel: { color: "rgba(255,255,255,0.4)", fontSize: 10, marginBottom: 6 },
  analyticsValue: { fontSize: 16, fontWeight: "800" },
  analyticsSub: { color: "rgba(255,255,255,0.35)", fontSize: 10, marginTop: 4 },
  analyticsLink: { marginTop: 14, borderRadius: 14, backgroundColor: "rgba(139,92,246,0.12)", paddingHorizontal: 14, paddingVertical: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  filterChip: { borderRadius: 999, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(255,255,255,0.06)", paddingHorizontal: 16, paddingVertical: 7 },
  filterChipText: { color: "rgba(255,255,255,0.5)", fontSize: 11, fontWeight: "700" },
  periodChip: { borderRadius: 10, borderWidth: 1, borderColor: "transparent", paddingHorizontal: 10, paddingVertical: 6 },
  periodChipText: { color: "rgba(255,255,255,0.35)", fontSize: 10, fontWeight: "700" },
  segmentedWrap: { flexDirection: "row", backgroundColor: "rgba(255,255,255,0.05)", borderRadius: 18, padding: 4, marginTop: 18 },
  segmentedOption: { flex: 1, minHeight: 38, borderRadius: 14, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "transparent" },
  segmentedOptionActive: { backgroundColor: "rgba(139,92,246,0.25)", borderColor: "rgba(139,92,246,0.35)" },
  segmentedText: { color: "rgba(255,255,255,0.4)", fontSize: 12, fontWeight: "700" },
  profileTop: { alignItems: "center", paddingTop: 8 },
  profileAvatarWrap: { position: "relative", marginBottom: 14 },
  profileAvatar: { width: 96, height: 96, borderRadius: 48, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.teal, ...{ shadowColor: COLORS.teal, shadowOpacity: 0.28, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 8 } },
  profileEditButton: { position: "absolute", right: 0, bottom: 0, width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: "#111d1b", borderWidth: 2, borderColor: COLORS.screen },
  profileStatsRow: { flexDirection: "row", alignItems: "stretch" },
  profileStatCell: { flex: 1, alignItems: "center", paddingVertical: 16, position: "relative" },
  profileStatValue: { fontSize: 20, fontWeight: "900" },
  profileStatLabel: { color: "rgba(255,255,255,0.4)", fontSize: 10, marginTop: 6 },
  profileStatDivider: { position: "absolute", right: 0, top: 18, bottom: 18, width: 1, backgroundColor: "rgba(255,255,255,0.07)" },
  achievementCard: { width: 110 },
  settingsRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 16, paddingVertical: 14 },
  rowDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.05)", marginHorizontal: 16 },
  logoutButton: { minHeight: 52, borderRadius: 18, borderWidth: 1, borderColor: "rgba(239,68,68,0.22)", backgroundColor: "rgba(239,68,68,0.08)", alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 },
  logoutText: { color: COLORS.red, fontSize: 14, fontWeight: "700" },
  footerText: { color: "rgba(255,255,255,0.18)", fontSize: 10, textAlign: "center", marginTop: 20 },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  optionChip: { borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(255,255,255,0.06)", paddingHorizontal: 12, paddingVertical: 10 },
  optionChipText: { color: "rgba(255,255,255,0.5)", fontSize: 12, fontWeight: "700", textAlign: "center" },
  bigMetric: { color: COLORS.text, fontSize: 40, fontWeight: "900" },
  modalMetricInput: { width: "100%", minHeight: 70, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.07)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", color: COLORS.text, fontSize: 28, fontWeight: "900", textAlign: "center" },
  deleteWrap: { width: 32, height: 32, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(239,68,68,0.1)" },
  settingsSectionPad: { paddingHorizontal: 16, paddingVertical: 14 },
  notificationRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 14, gap: 14 },
  dangerZone: { minHeight: 74, borderRadius: 18, borderWidth: 1, borderColor: "rgba(239,68,68,0.2)", backgroundColor: "rgba(239,68,68,0.06)", paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12, marginTop: 10 },
  listMeta: { color: "rgba(255,255,255,0.34)", fontSize: 10 },
  inputLabel: { color: "rgba(255,255,255,0.5)", fontSize: 12, fontWeight: "600", marginBottom: 6 },
  textArea: { width: "100%", minHeight: 80, borderRadius: 14, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", color: COLORS.text, paddingHorizontal: 16, paddingVertical: 12, fontSize: 14, textAlignVertical: "top" },
});
