/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  HTTPValidationError,
  ListPersonalRecordsPersonalRecordsGetParams,
  PersonalRecordResponse
} from '../../model';


export type listPersonalRecordsPersonalRecordsGetResponse200 = {
  data: PersonalRecordResponse[]
  status: 200
}

export type listPersonalRecordsPersonalRecordsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listPersonalRecordsPersonalRecordsGetResponseSuccess = (listPersonalRecordsPersonalRecordsGetResponse200) & {
  headers: Headers;
};
export type listPersonalRecordsPersonalRecordsGetResponseError = (listPersonalRecordsPersonalRecordsGetResponse422) & {
  headers: Headers;
};

export type listPersonalRecordsPersonalRecordsGetResponse = (listPersonalRecordsPersonalRecordsGetResponseSuccess | listPersonalRecordsPersonalRecordsGetResponseError)

export const getListPersonalRecordsPersonalRecordsGetUrl = (params?: ListPersonalRecordsPersonalRecordsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/personal-records?${stringifiedParams}` : `/personal-records`
}

/**
 * @summary List Personal Records
 */
export const listPersonalRecordsPersonalRecordsGet = async (params?: ListPersonalRecordsPersonalRecordsGetParams, options?: RequestInit): Promise<listPersonalRecordsPersonalRecordsGetResponse> => {

  const res = await fetch(getListPersonalRecordsPersonalRecordsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listPersonalRecordsPersonalRecordsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPersonalRecordsPersonalRecordsGetResponse
}


export type getPersonalRecordPersonalRecordsRecordIdGetResponse200 = {
  data: PersonalRecordResponse
  status: 200
}

export type getPersonalRecordPersonalRecordsRecordIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getPersonalRecordPersonalRecordsRecordIdGetResponseSuccess = (getPersonalRecordPersonalRecordsRecordIdGetResponse200) & {
  headers: Headers;
};
export type getPersonalRecordPersonalRecordsRecordIdGetResponseError = (getPersonalRecordPersonalRecordsRecordIdGetResponse422) & {
  headers: Headers;
};

export type getPersonalRecordPersonalRecordsRecordIdGetResponse = (getPersonalRecordPersonalRecordsRecordIdGetResponseSuccess | getPersonalRecordPersonalRecordsRecordIdGetResponseError)

export const getGetPersonalRecordPersonalRecordsRecordIdGetUrl = (recordId: number,) => {




  return `/personal-records/${recordId}`
}

/**
 * @summary Get Personal Record
 */
export const getPersonalRecordPersonalRecordsRecordIdGet = async (recordId: number, options?: RequestInit): Promise<getPersonalRecordPersonalRecordsRecordIdGetResponse> => {

  const res = await fetch(getGetPersonalRecordPersonalRecordsRecordIdGetUrl(recordId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPersonalRecordPersonalRecordsRecordIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPersonalRecordPersonalRecordsRecordIdGetResponse
}


