export const queryKeys = {
  appConfig: ["meta", "app-config"] as const,
  health: ["health"] as const,
  authMe: ["auth", "me"] as const,
  overview: ["users", "me", "overview"] as const,
  currentUser: ["users", "me"] as const,
  profile: ["users", "me", "profile"] as const,
  bodyWeightLogs: ["users", "me", "body-weight-logs"] as const,
  exercises: (params?: unknown) => ["exercises", params ?? {}] as const,
  exerciseFilters: ["exercises", "filters"] as const,
  exerciseDetail: (id?: string) => ["exercises", id] as const,
  templates: ["workout-templates"] as const,
  templateDetail: (id?: number | null) => ["workout-templates", id] as const,
  sessions: (params?: unknown) => ["workout-sessions", params ?? {}] as const,
  sessionDetail: (id?: number | null) => ["workout-sessions", id] as const,
  personalRecords: (params?: unknown) => ["personal-records", params ?? {}] as const,
  exerciseProgress: (id?: string, params?: unknown) => ["progress", id, params ?? {}] as const,
  muscleBalance: (params?: unknown) => ["analytics", "muscle-balance", params ?? {}] as const,
  notificationSettings: ["notifications", "settings"] as const,
  mesocycles: ["mesocycles"] as const,
  mesocycleDetail: (id?: number | null) => ["mesocycles", id] as const,
  mesocycleAnalytics: (id?: number | null, params?: unknown) => ["mesocycles", id, "analytics", params ?? {}] as const,
};
