/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WorkoutTemplateCreate,
  WorkoutTemplateDetailResponse,
  WorkoutTemplateExerciseCreate,
  WorkoutTemplateExerciseResponse,
  WorkoutTemplateExerciseUpdate,
  WorkoutTemplateResponse,
  WorkoutTemplateUpdate
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type listWorkoutTemplatesWorkoutTemplatesGetResponse200 = {
  data: WorkoutTemplateResponse[]
  status: 200
}

export type listWorkoutTemplatesWorkoutTemplatesGetResponseSuccess = (listWorkoutTemplatesWorkoutTemplatesGetResponse200) & {
  headers: Headers;
};
;

export type listWorkoutTemplatesWorkoutTemplatesGetResponse = (listWorkoutTemplatesWorkoutTemplatesGetResponseSuccess)

export const getListWorkoutTemplatesWorkoutTemplatesGetUrl = () => {




  return `/workout-templates`
}

/**
 * @summary List Workout Templates
 */
export const listWorkoutTemplatesWorkoutTemplatesGet = async ( options?: RequestInit): Promise<listWorkoutTemplatesWorkoutTemplatesGetResponse> => {

  return apiMutator<listWorkoutTemplatesWorkoutTemplatesGetResponse>(getListWorkoutTemplatesWorkoutTemplatesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getListWorkoutTemplatesWorkoutTemplatesGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>, TError,void, TContext> => {

const mutationKey = ['listWorkoutTemplatesWorkoutTemplatesGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>, void> = () => {


          return  listWorkoutTemplatesWorkoutTemplatesGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListWorkoutTemplatesWorkoutTemplatesGetMutationResult = NonNullable<Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>>

    export type ListWorkoutTemplatesWorkoutTemplatesGetMutationError = unknown

    /**
 * @summary List Workout Templates
 */
export const useListWorkoutTemplatesWorkoutTemplatesGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listWorkoutTemplatesWorkoutTemplatesGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getListWorkoutTemplatesWorkoutTemplatesGetMutationOptions(options), queryClient);
    }
    export type createWorkoutTemplateWorkoutTemplatesPostResponse201 = {
  data: WorkoutTemplateResponse
  status: 201
}

export type createWorkoutTemplateWorkoutTemplatesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createWorkoutTemplateWorkoutTemplatesPostResponseSuccess = (createWorkoutTemplateWorkoutTemplatesPostResponse201) & {
  headers: Headers;
};
export type createWorkoutTemplateWorkoutTemplatesPostResponseError = (createWorkoutTemplateWorkoutTemplatesPostResponse422) & {
  headers: Headers;
};

export type createWorkoutTemplateWorkoutTemplatesPostResponse = (createWorkoutTemplateWorkoutTemplatesPostResponseSuccess | createWorkoutTemplateWorkoutTemplatesPostResponseError)

export const getCreateWorkoutTemplateWorkoutTemplatesPostUrl = () => {




  return `/workout-templates`
}

/**
 * @summary Create Workout Template
 */
export const createWorkoutTemplateWorkoutTemplatesPost = async (workoutTemplateCreate: WorkoutTemplateCreate, options?: RequestInit): Promise<createWorkoutTemplateWorkoutTemplatesPostResponse> => {

  return apiMutator<createWorkoutTemplateWorkoutTemplatesPostResponse>(getCreateWorkoutTemplateWorkoutTemplatesPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutTemplateCreate)
  }
);}





export const getCreateWorkoutTemplateWorkoutTemplatesPostQueryKey = (workoutTemplateCreate?: WorkoutTemplateCreate,) => {
    return [
    'POST', `/workout-templates`, workoutTemplateCreate
    ] as const;
    }


export const getCreateWorkoutTemplateWorkoutTemplatesPostQueryOptions = <TData = Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError = HTTPValidationError>(workoutTemplateCreate: WorkoutTemplateCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateWorkoutTemplateWorkoutTemplatesPostQueryKey(workoutTemplateCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>> = ({ signal }) => createWorkoutTemplateWorkoutTemplatesPost(workoutTemplateCreate, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateWorkoutTemplateWorkoutTemplatesPostQueryResult = NonNullable<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>>
export type CreateWorkoutTemplateWorkoutTemplatesPostQueryError = HTTPValidationError


export function useCreateWorkoutTemplateWorkoutTemplatesPost<TData = Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError = HTTPValidationError>(
 workoutTemplateCreate: WorkoutTemplateCreate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>,
          TError,
          Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateWorkoutTemplateWorkoutTemplatesPost<TData = Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError = HTTPValidationError>(
 workoutTemplateCreate: WorkoutTemplateCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>,
          TError,
          Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateWorkoutTemplateWorkoutTemplatesPost<TData = Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError = HTTPValidationError>(
 workoutTemplateCreate: WorkoutTemplateCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Workout Template
 */

export function useCreateWorkoutTemplateWorkoutTemplatesPost<TData = Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError = HTTPValidationError>(
 workoutTemplateCreate: WorkoutTemplateCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createWorkoutTemplateWorkoutTemplatesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateWorkoutTemplateWorkoutTemplatesPostQueryOptions(workoutTemplateCreate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse200 = {
  data: WorkoutTemplateDetailResponse
  status: 200
}

export type getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponseSuccess = (getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse200) & {
  headers: Headers;
};
export type getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponseError = (getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse422) & {
  headers: Headers;
};

export type getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse = (getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponseSuccess | getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponseError)

export const getGetWorkoutTemplateWorkoutTemplatesTemplateIdGetUrl = (templateId: number,) => {




  return `/workout-templates/${templateId}`
}

/**
 * @summary Get Workout Template
 */
export const getWorkoutTemplateWorkoutTemplatesTemplateIdGet = async (templateId: number, options?: RequestInit): Promise<getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse> => {

  return apiMutator<getWorkoutTemplateWorkoutTemplatesTemplateIdGetResponse>(getGetWorkoutTemplateWorkoutTemplatesTemplateIdGetUrl(templateId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetWorkoutTemplateWorkoutTemplatesTemplateIdGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>, TError,{templateId: number}, TContext> => {

const mutationKey = ['getWorkoutTemplateWorkoutTemplatesTemplateIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>, {templateId: number}> = (props) => {
          const {templateId} = props ?? {};

          return  getWorkoutTemplateWorkoutTemplatesTemplateIdGet(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetWorkoutTemplateWorkoutTemplatesTemplateIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>>

    export type GetWorkoutTemplateWorkoutTemplatesTemplateIdGetMutationError = HTTPValidationError

    /**
 * @summary Get Workout Template
 */
export const useGetWorkoutTemplateWorkoutTemplatesTemplateIdGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getWorkoutTemplateWorkoutTemplatesTemplateIdGet>>,
        TError,
        {templateId: number},
        TContext
      > => {
      return useMutation(getGetWorkoutTemplateWorkoutTemplatesTemplateIdGetMutationOptions(options), queryClient);
    }
    export type updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse200 = {
  data: WorkoutTemplateResponse
  status: 200
}

export type updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponseSuccess = (updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse200) & {
  headers: Headers;
};
export type updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponseError = (updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse422) & {
  headers: Headers;
};

export type updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse = (updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponseSuccess | updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponseError)

export const getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchUrl = (templateId: number,) => {




  return `/workout-templates/${templateId}`
}

/**
 * @summary Update Workout Template
 */
export const updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch = async (templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options?: RequestInit): Promise<updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse> => {

  return apiMutator<updateWorkoutTemplateWorkoutTemplatesTemplateIdPatchResponse>(getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchUrl(templateId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutTemplateUpdate)
  }
);}





export const getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryKey = (templateId: number,
    workoutTemplateUpdate?: WorkoutTemplateUpdate,) => {
    return [
    'PATCH', `/workout-templates/${templateId}`, workoutTemplateUpdate
    ] as const;
    }


export const getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError = HTTPValidationError>(templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryKey(templateId,workoutTemplateUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>> = ({ signal }) => updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch(templateId,workoutTemplateUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>>
export type UpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryError = HTTPValidationError


export function useUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatch<TData = Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatch<TData = Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatch<TData = Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Workout Template
 */

export function useUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatch<TData = Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateUpdate: WorkoutTemplateUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateWorkoutTemplateWorkoutTemplatesTemplateIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateWorkoutTemplateWorkoutTemplatesTemplateIdPatchQueryOptions(templateId,workoutTemplateUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponseSuccess = (deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponseError = (deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse = (deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponseSuccess | deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponseError)

export const getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteUrl = (templateId: number,) => {




  return `/workout-templates/${templateId}`
}

/**
 * @summary Delete Workout Template
 */
export const deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete = async (templateId: number, options?: RequestInit): Promise<deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse> => {

  return apiMutator<deleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteResponse>(getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteUrl(templateId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryKey = (templateId: number,) => {
    return [
    'DELETE', `/workout-templates/${templateId}`
    ] as const;
    }


export const getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError = HTTPValidationError>(templateId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryKey(templateId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>> = ({ signal }) => deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete(templateId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>>
export type DeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryError = HTTPValidationError


export function useDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete<TData = Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError = HTTPValidationError>(
 templateId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete<TData = Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError = HTTPValidationError>(
 templateId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete<TData = Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError = HTTPValidationError>(
 templateId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Workout Template
 */

export function useDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete<TData = Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError = HTTPValidationError>(
 templateId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteWorkoutTemplateWorkoutTemplatesTemplateIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteWorkoutTemplateWorkoutTemplatesTemplateIdDeleteQueryOptions(templateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse200 = {
  data: WorkoutTemplateExerciseResponse[]
  status: 200
}

export type listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponseSuccess = (listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse200) & {
  headers: Headers;
};
export type listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponseError = (listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse422) & {
  headers: Headers;
};

export type listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse = (listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponseSuccess | listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponseError)

export const getListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetUrl = (templateId: number,) => {




  return `/workout-templates/${templateId}/exercises`
}

/**
 * @summary List Template Exercises
 */
export const listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet = async (templateId: number, options?: RequestInit): Promise<listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse> => {

  return apiMutator<listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetResponse>(getListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetUrl(templateId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>, TError,{templateId: number}, TContext> => {

const mutationKey = ['listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>, {templateId: number}> = (props) => {
          const {templateId} = props ?? {};

          return  listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet(templateId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetMutationResult = NonNullable<Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>>

    export type ListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetMutationError = HTTPValidationError

    /**
 * @summary List Template Exercises
 */
export const useListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>, TError,{templateId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listTemplateExercisesWorkoutTemplatesTemplateIdExercisesGet>>,
        TError,
        {templateId: number},
        TContext
      > => {
      return useMutation(getListTemplateExercisesWorkoutTemplatesTemplateIdExercisesGetMutationOptions(options), queryClient);
    }
    export type createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse201 = {
  data: WorkoutTemplateExerciseResponse
  status: 201
}

export type createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponseSuccess = (createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse201) & {
  headers: Headers;
};
export type createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponseError = (createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse422) & {
  headers: Headers;
};

export type createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse = (createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponseSuccess | createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponseError)

export const getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostUrl = (templateId: number,) => {




  return `/workout-templates/${templateId}/exercises`
}

/**
 * @summary Create Template Exercise
 */
export const createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost = async (templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options?: RequestInit): Promise<createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse> => {

  return apiMutator<createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostResponse>(getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostUrl(templateId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutTemplateExerciseCreate)
  }
);}





export const getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryKey = (templateId: number,
    workoutTemplateExerciseCreate?: WorkoutTemplateExerciseCreate,) => {
    return [
    'POST', `/workout-templates/${templateId}/exercises`, workoutTemplateExerciseCreate
    ] as const;
    }


export const getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryOptions = <TData = Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError = HTTPValidationError>(templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryKey(templateId,workoutTemplateExerciseCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>> = ({ signal }) => createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost(templateId,workoutTemplateExerciseCreate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryResult = NonNullable<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>>
export type CreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryError = HTTPValidationError


export function useCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost<TData = Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>,
          TError,
          Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost<TData = Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>,
          TError,
          Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost<TData = Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Template Exercise
 */

export function useCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost<TData = Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError = HTTPValidationError>(
 templateId: number,
    workoutTemplateExerciseCreate: WorkoutTemplateExerciseCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createTemplateExerciseWorkoutTemplatesTemplateIdExercisesPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateTemplateExerciseWorkoutTemplatesTemplateIdExercisesPostQueryOptions(templateId,workoutTemplateExerciseCreate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse200 = {
  data: WorkoutTemplateExerciseResponse
  status: 200
}

export type getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponseSuccess = (getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse200) & {
  headers: Headers;
};
export type getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponseError = (getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse422) & {
  headers: Headers;
};

export type getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse = (getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponseSuccess | getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponseError)

export const getGetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetUrl = (templateId: number,
    templateExerciseId: number,) => {




  return `/workout-templates/${templateId}/exercises/${templateExerciseId}`
}

/**
 * @summary Get Template Exercise
 */
export const getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet = async (templateId: number,
    templateExerciseId: number, options?: RequestInit): Promise<getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse> => {

  return apiMutator<getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetResponse>(getGetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetUrl(templateId,templateExerciseId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>, TError,{templateId: number;templateExerciseId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>, TError,{templateId: number;templateExerciseId: number}, TContext> => {

const mutationKey = ['getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>, {templateId: number;templateExerciseId: number}> = (props) => {
          const {templateId,templateExerciseId} = props ?? {};

          return  getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet(templateId,templateExerciseId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>>

    export type GetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetMutationError = HTTPValidationError

    /**
 * @summary Get Template Exercise
 */
export const useGetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>, TError,{templateId: number;templateExerciseId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGet>>,
        TError,
        {templateId: number;templateExerciseId: number},
        TContext
      > => {
      return useMutation(getGetTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdGetMutationOptions(options), queryClient);
    }
    export type updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse200 = {
  data: WorkoutTemplateExerciseResponse
  status: 200
}

export type updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponseSuccess = (updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse200) & {
  headers: Headers;
};
export type updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponseError = (updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse422) & {
  headers: Headers;
};

export type updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse = (updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponseSuccess | updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponseError)

export const getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchUrl = (templateId: number,
    templateExerciseId: number,) => {




  return `/workout-templates/${templateId}/exercises/${templateExerciseId}`
}

/**
 * @summary Update Template Exercise
 */
export const updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch = async (templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options?: RequestInit): Promise<updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse> => {

  return apiMutator<updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchResponse>(getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchUrl(templateId,templateExerciseId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutTemplateExerciseUpdate)
  }
);}





export const getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryKey = (templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate?: WorkoutTemplateExerciseUpdate,) => {
    return [
    'PATCH', `/workout-templates/${templateId}/exercises/${templateExerciseId}`, workoutTemplateExerciseUpdate
    ] as const;
    }


export const getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError = HTTPValidationError>(templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryKey(templateId,templateExerciseId,workoutTemplateExerciseUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>> = ({ signal }) => updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch(templateId,templateExerciseId,workoutTemplateExerciseUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined && templateExerciseId !== null && templateExerciseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>>
export type UpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryError = HTTPValidationError


export function useUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch<TData = Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch<TData = Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch<TData = Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Template Exercise
 */

export function useUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch<TData = Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number,
    workoutTemplateExerciseUpdate: WorkoutTemplateExerciseUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdPatchQueryOptions(templateId,templateExerciseId,workoutTemplateExerciseUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponseSuccess = (deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponseError = (deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse = (deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponseSuccess | deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponseError)

export const getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteUrl = (templateId: number,
    templateExerciseId: number,) => {




  return `/workout-templates/${templateId}/exercises/${templateExerciseId}`
}

/**
 * @summary Delete Template Exercise
 */
export const deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete = async (templateId: number,
    templateExerciseId: number, options?: RequestInit): Promise<deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse> => {

  return apiMutator<deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteResponse>(getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteUrl(templateId,templateExerciseId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryKey = (templateId: number,
    templateExerciseId: number,) => {
    return [
    'DELETE', `/workout-templates/${templateId}/exercises/${templateExerciseId}`
    ] as const;
    }


export const getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError = HTTPValidationError>(templateId: number,
    templateExerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryKey(templateId,templateExerciseId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>> = ({ signal }) => deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete(templateId,templateExerciseId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: templateId !== null && templateId !== undefined && templateExerciseId !== null && templateExerciseId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>>
export type DeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryError = HTTPValidationError


export function useDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete<TData = Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete<TData = Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete<TData = Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Template Exercise
 */

export function useDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete<TData = Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError = HTTPValidationError>(
 templateId: number,
    templateExerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteTemplateExerciseWorkoutTemplatesTemplateIdExercisesTemplateExerciseIdDeleteQueryOptions(templateId,templateExerciseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






