/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WaitlistRequest,
  WaitlistResponse
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type submitWaitlistWaitlistPostResponse200 = {
  data: WaitlistResponse
  status: 200
}

export type submitWaitlistWaitlistPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type submitWaitlistWaitlistPostResponseSuccess = (submitWaitlistWaitlistPostResponse200) & {
  headers: Headers;
};
export type submitWaitlistWaitlistPostResponseError = (submitWaitlistWaitlistPostResponse422) & {
  headers: Headers;
};

export type submitWaitlistWaitlistPostResponse = (submitWaitlistWaitlistPostResponseSuccess | submitWaitlistWaitlistPostResponseError)

export const getSubmitWaitlistWaitlistPostUrl = () => {




  return `/waitlist`
}

/**
 * @summary Submit Waitlist
 */
export const submitWaitlistWaitlistPost = async (waitlistRequest: WaitlistRequest, options?: RequestInit): Promise<submitWaitlistWaitlistPostResponse> => {

  return apiMutator<submitWaitlistWaitlistPostResponse>(getSubmitWaitlistWaitlistPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(waitlistRequest)
  }
);}





export const getSubmitWaitlistWaitlistPostQueryKey = (waitlistRequest?: WaitlistRequest,) => {
    return [
    'POST', `/waitlist`, waitlistRequest
    ] as const;
    }


export const getSubmitWaitlistWaitlistPostQueryOptions = <TData = Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError = HTTPValidationError>(waitlistRequest: WaitlistRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSubmitWaitlistWaitlistPostQueryKey(waitlistRequest);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>> = ({ signal }) => submitWaitlistWaitlistPost(waitlistRequest, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SubmitWaitlistWaitlistPostQueryResult = NonNullable<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>>
export type SubmitWaitlistWaitlistPostQueryError = HTTPValidationError


export function useSubmitWaitlistWaitlistPost<TData = Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError = HTTPValidationError>(
 waitlistRequest: WaitlistRequest, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>,
          TError,
          Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubmitWaitlistWaitlistPost<TData = Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError = HTTPValidationError>(
 waitlistRequest: WaitlistRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>,
          TError,
          Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSubmitWaitlistWaitlistPost<TData = Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError = HTTPValidationError>(
 waitlistRequest: WaitlistRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Submit Waitlist
 */

export function useSubmitWaitlistWaitlistPost<TData = Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError = HTTPValidationError>(
 waitlistRequest: WaitlistRequest, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof submitWaitlistWaitlistPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSubmitWaitlistWaitlistPostQueryOptions(waitlistRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






