/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ExerciseProgressResponse,
  GetExerciseProgressProgressExerciseIdGetParams,
  HTTPValidationError
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getExerciseProgressProgressExerciseIdGetResponse200 = {
  data: ExerciseProgressResponse
  status: 200
}

export type getExerciseProgressProgressExerciseIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseProgressProgressExerciseIdGetResponseSuccess = (getExerciseProgressProgressExerciseIdGetResponse200) & {
  headers: Headers;
};
export type getExerciseProgressProgressExerciseIdGetResponseError = (getExerciseProgressProgressExerciseIdGetResponse422) & {
  headers: Headers;
};

export type getExerciseProgressProgressExerciseIdGetResponse = (getExerciseProgressProgressExerciseIdGetResponseSuccess | getExerciseProgressProgressExerciseIdGetResponseError)

export const getGetExerciseProgressProgressExerciseIdGetUrl = (exerciseId: string,
    params?: GetExerciseProgressProgressExerciseIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/progress/${exerciseId}?${stringifiedParams}` : `/progress/${exerciseId}`
}

/**
 * @summary Get Exercise Progress
 */
export const getExerciseProgressProgressExerciseIdGet = async (exerciseId: string,
    params?: GetExerciseProgressProgressExerciseIdGetParams, options?: RequestInit): Promise<getExerciseProgressProgressExerciseIdGetResponse> => {

  return apiMutator<getExerciseProgressProgressExerciseIdGetResponse>(getGetExerciseProgressProgressExerciseIdGetUrl(exerciseId,params),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetExerciseProgressProgressExerciseIdGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>, TError,{exerciseId: string;params?: GetExerciseProgressProgressExerciseIdGetParams}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>, TError,{exerciseId: string;params?: GetExerciseProgressProgressExerciseIdGetParams}, TContext> => {

const mutationKey = ['getExerciseProgressProgressExerciseIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>, {exerciseId: string;params?: GetExerciseProgressProgressExerciseIdGetParams}> = (props) => {
          const {exerciseId,params} = props ?? {};

          return  getExerciseProgressProgressExerciseIdGet(exerciseId,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetExerciseProgressProgressExerciseIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>>

    export type GetExerciseProgressProgressExerciseIdGetMutationError = HTTPValidationError

    /**
 * @summary Get Exercise Progress
 */
export const useGetExerciseProgressProgressExerciseIdGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>, TError,{exerciseId: string;params?: GetExerciseProgressProgressExerciseIdGetParams}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getExerciseProgressProgressExerciseIdGet>>,
        TError,
        {exerciseId: string;params?: GetExerciseProgressProgressExerciseIdGetParams},
        TContext
      > => {
      return useMutation(getGetExerciseProgressProgressExerciseIdGetMutationOptions(options), queryClient);
    }
