/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  AppConfigResponse
} from '../../model';


export type getAppConfigMetaAppConfigGetResponse200 = {
  data: AppConfigResponse
  status: 200
}

export type getAppConfigMetaAppConfigGetResponseSuccess = (getAppConfigMetaAppConfigGetResponse200) & {
  headers: Headers;
};
;

export type getAppConfigMetaAppConfigGetResponse = (getAppConfigMetaAppConfigGetResponseSuccess)

export const getGetAppConfigMetaAppConfigGetUrl = () => {




  return `/meta/app-config`
}

/**
 * @summary Get App Config
 */
export const getAppConfigMetaAppConfigGet = async ( options?: RequestInit): Promise<getAppConfigMetaAppConfigGetResponse> => {

  const res = await fetch(getGetAppConfigMetaAppConfigGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAppConfigMetaAppConfigGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAppConfigMetaAppConfigGetResponse
}


