/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  ExerciseDetailResponse,
  ExerciseFiltersResponse,
  ExerciseListResponse,
  HTTPValidationError,
  ListExercisesExercisesGetParams
} from '../../model';


export type listExercisesExercisesGetResponse200 = {
  data: ExerciseListResponse
  status: 200
}

export type listExercisesExercisesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExercisesExercisesGetResponseSuccess = (listExercisesExercisesGetResponse200) & {
  headers: Headers;
};
export type listExercisesExercisesGetResponseError = (listExercisesExercisesGetResponse422) & {
  headers: Headers;
};

export type listExercisesExercisesGetResponse = (listExercisesExercisesGetResponseSuccess | listExercisesExercisesGetResponseError)

export const getListExercisesExercisesGetUrl = (params?: ListExercisesExercisesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/exercises?${stringifiedParams}` : `/exercises`
}

/**
 * @summary List Exercises
 */
export const listExercisesExercisesGet = async (params?: ListExercisesExercisesGetParams, options?: RequestInit): Promise<listExercisesExercisesGetResponse> => {

  const res = await fetch(getListExercisesExercisesGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listExercisesExercisesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listExercisesExercisesGetResponse
}


export type getExerciseFiltersExercisesFiltersGetResponse200 = {
  data: ExerciseFiltersResponse
  status: 200
}

export type getExerciseFiltersExercisesFiltersGetResponseSuccess = (getExerciseFiltersExercisesFiltersGetResponse200) & {
  headers: Headers;
};
;

export type getExerciseFiltersExercisesFiltersGetResponse = (getExerciseFiltersExercisesFiltersGetResponseSuccess)

export const getGetExerciseFiltersExercisesFiltersGetUrl = () => {




  return `/exercises/filters`
}

/**
 * @summary Get Exercise Filters
 */
export const getExerciseFiltersExercisesFiltersGet = async ( options?: RequestInit): Promise<getExerciseFiltersExercisesFiltersGetResponse> => {

  const res = await fetch(getGetExerciseFiltersExercisesFiltersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getExerciseFiltersExercisesFiltersGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getExerciseFiltersExercisesFiltersGetResponse
}


export type getExerciseExercisesExerciseIdGetResponse200 = {
  data: ExerciseDetailResponse
  status: 200
}

export type getExerciseExercisesExerciseIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseExercisesExerciseIdGetResponseSuccess = (getExerciseExercisesExerciseIdGetResponse200) & {
  headers: Headers;
};
export type getExerciseExercisesExerciseIdGetResponseError = (getExerciseExercisesExerciseIdGetResponse422) & {
  headers: Headers;
};

export type getExerciseExercisesExerciseIdGetResponse = (getExerciseExercisesExerciseIdGetResponseSuccess | getExerciseExercisesExerciseIdGetResponseError)

export const getGetExerciseExercisesExerciseIdGetUrl = (exerciseId: string,) => {




  return `/exercises/${exerciseId}`
}

/**
 * @summary Get Exercise
 */
export const getExerciseExercisesExerciseIdGet = async (exerciseId: string, options?: RequestInit): Promise<getExerciseExercisesExerciseIdGetResponse> => {

  const res = await fetch(getGetExerciseExercisesExerciseIdGetUrl(exerciseId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getExerciseExercisesExerciseIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getExerciseExercisesExerciseIdGetResponse
}


