/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface AppFeaturesResponse {
  auth: boolean;
  user_profiles: boolean;
  body_weight_tracking: boolean;
  exercises: boolean;
  workout_templates: boolean;
  workout_sessions: boolean;
  personal_records: boolean;
  progress_tracking: boolean;
  mesocycles: boolean;
  deload_suggestions: boolean;
  muscle_balance_reports: boolean;
}
