/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponse } from './userResponse';

export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  /** Access token lifetime in seconds */
  expires_in: number;
  /** Refresh token lifetime in seconds */
  refresh_expires_in: number;
  user: UserResponse;
}
