/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface BodyWeightLogCreate {
  /** @exclusiveMinimum 0 */
  weight_kg: number;
  logged_at: string;
  notes?: string | null;
}
