/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface ExerciseSetUpdate {
  exercise_id?: string | null;
  set_number?: number | null;
  set_type?: string | null;
  reps?: number | null;
  weight_kg?: number | null;
  duration_sec?: number | null;
  distance_m?: number | null;
  rpe?: number | null;
  is_pr?: boolean | null;
  notes?: string | null;
  logged_at?: string | null;
}
