/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface ExerciseBlockComparisonResponse {
  exercise_id: string;
  exercise_name: string;
  current_completed_sets: number;
  previous_completed_sets: number;
  completed_sets_delta: number;
  current_total_volume_load: number;
  previous_total_volume_load: number;
  total_volume_load_delta: number;
  current_best_e1rm: number | null;
  previous_best_e1rm: number | null;
  best_e1rm_delta: number | null;
}
