/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackType } from './feedbackType';

export interface FeedbackCreate {
  type: FeedbackType;
  title?: string | null;
  description: string;
  category?: string | null;
}
