/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { FeedbackStatus } from './feedbackStatus';
import type { FeedbackType } from './feedbackType';
import type { FeedbackUserBrief } from './feedbackUserBrief';

export interface FeedbackResponse {
  id: number;
  type: FeedbackType;
  title: string | null;
  description: string;
  category: string | null;
  status: FeedbackStatus;
  admin_notes: string | null;
  is_public: boolean;
  upvotes_count: number;
  has_upvoted?: boolean | null;
  comment_count?: number;
  user: FeedbackUserBrief;
  created_at: string;
  updated_at: string;
}
