/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export type FeedbackStatus = typeof FeedbackStatus[keyof typeof FeedbackStatus];


export const FeedbackStatus = {
  under_review: 'under_review',
  planned: 'planned',
  in_progress: 'in_progress',
  completed: 'completed',
  declined: 'declined',
} as const;
