/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export type FeedbackType = typeof FeedbackType[keyof typeof FeedbackType];


export const FeedbackType = {
  feature_request: 'feature_request',
  bug_report: 'bug_report',
  review: 'review',
} as const;
