/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { DeloadSuggestionResponse } from './deloadSuggestionResponse';
import type { ExerciseBlockComparisonResponse } from './exerciseBlockComparisonResponse';
import type { MesocycleResponse } from './mesocycleResponse';
import type { MuscleBalanceReportResponse } from './muscleBalanceReportResponse';
import type { TrainingBlockDeltaResponse } from './trainingBlockDeltaResponse';
import type { TrainingBlockSummaryResponse } from './trainingBlockSummaryResponse';

export interface MesocycleAnalyticsResponse {
  mesocycle: MesocycleResponse;
  previous_mesocycle: MesocycleResponse | null;
  current_block_summary: TrainingBlockSummaryResponse;
  previous_block_summary: TrainingBlockSummaryResponse | null;
  comparison_to_previous: TrainingBlockDeltaResponse | null;
  deload_suggestion: DeloadSuggestionResponse;
  exercise_comparisons: ExerciseBlockComparisonResponse[];
  muscle_balance: MuscleBalanceReportResponse;
}
