/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface MesocycleCreate {
  name: string;
  goal?: string | null;
  started_on: string;
  ended_on?: string | null;
  weeks?: number | null;
  notes?: string | null;
}
