/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface RegisterRequest {
  /**
     * @minLength 3
     * @maxLength 50
     * @pattern ^[A-Za-z0-9_.-]+$
     */
  username: string;
  /**
     * @minLength 6
     * @maxLength 254
     * @pattern ^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)+$
     */
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
}
