/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type { BodyWeightLogResponse } from './bodyWeightLogResponse';
import type { MesocycleResponse } from './mesocycleResponse';
import type { PersonalRecordResponse } from './personalRecordResponse';
import type { UserOverviewStatsResponse } from './userOverviewStatsResponse';
import type { UserProfileResponse } from './userProfileResponse';
import type { UserResponse } from './userResponse';
import type { WeeklyActivityDayResponse } from './weeklyActivityDayResponse';
import type { WorkoutSessionResponse } from './workoutSessionResponse';
import type { WorkoutStreaksResponse } from './workoutStreaksResponse';

export interface UserOverviewResponse {
  user: UserResponse;
  has_profile: boolean;
  profile: UserProfileResponse | null;
  latest_body_weight_log: BodyWeightLogResponse | null;
  active_mesocycle: MesocycleResponse | null;
  latest_completed_session: WorkoutSessionResponse | null;
  recent_personal_records: PersonalRecordResponse[];
  workout_streaks: WorkoutStreaksResponse;
  stats: UserOverviewStatsResponse;
  weekly_activity: WeeklyActivityDayResponse[];
}
