/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */

export interface WorkoutSessionUpdate {
  template_id?: number | null;
  mesocycle_id?: number | null;
  name?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
  perceived_exertion?: number | null;
  mood?: string | null;
  location?: string | null;
  notes?: string | null;
  is_completed?: boolean | null;
}
