/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyWeightLogCreate,
  BodyWeightLogResponse,
  BodyWeightLogUpdate,
  HTTPValidationError,
  UserOverviewResponse,
  UserProfileResponse,
  UserProfileUpdate,
  UserResponse,
  UserUpdate
} from '../../model';

import { apiMutator } from '../../client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getCurrentUserDetailsUsersMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getCurrentUserDetailsUsersMeGetResponseSuccess = (getCurrentUserDetailsUsersMeGetResponse200) & {
  headers: Headers;
};
;

export type getCurrentUserDetailsUsersMeGetResponse = (getCurrentUserDetailsUsersMeGetResponseSuccess)

export const getGetCurrentUserDetailsUsersMeGetUrl = () => {




  return `/users/me`
}

/**
 * @summary Get Current User Details
 */
export const getCurrentUserDetailsUsersMeGet = async ( options?: RequestInit): Promise<getCurrentUserDetailsUsersMeGetResponse> => {

  return apiMutator<getCurrentUserDetailsUsersMeGetResponse>(getGetCurrentUserDetailsUsersMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetCurrentUserDetailsUsersMeGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>, TError,void, TContext> => {

const mutationKey = ['getCurrentUserDetailsUsersMeGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>, void> = () => {


          return  getCurrentUserDetailsUsersMeGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCurrentUserDetailsUsersMeGetMutationResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>>

    export type GetCurrentUserDetailsUsersMeGetMutationError = unknown

    /**
 * @summary Get Current User Details
 */
export const useGetCurrentUserDetailsUsersMeGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCurrentUserDetailsUsersMeGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetCurrentUserDetailsUsersMeGetMutationOptions(options), queryClient);
    }
    export type updateCurrentUserUsersMePatchResponse200 = {
  data: UserResponse
  status: 200
}

export type updateCurrentUserUsersMePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateCurrentUserUsersMePatchResponseSuccess = (updateCurrentUserUsersMePatchResponse200) & {
  headers: Headers;
};
export type updateCurrentUserUsersMePatchResponseError = (updateCurrentUserUsersMePatchResponse422) & {
  headers: Headers;
};

export type updateCurrentUserUsersMePatchResponse = (updateCurrentUserUsersMePatchResponseSuccess | updateCurrentUserUsersMePatchResponseError)

export const getUpdateCurrentUserUsersMePatchUrl = () => {




  return `/users/me`
}

/**
 * @summary Update Current User
 */
export const updateCurrentUserUsersMePatch = async (userUpdate: UserUpdate, options?: RequestInit): Promise<updateCurrentUserUsersMePatchResponse> => {

  return apiMutator<updateCurrentUserUsersMePatchResponse>(getUpdateCurrentUserUsersMePatchUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userUpdate)
  }
);}





export const getUpdateCurrentUserUsersMePatchQueryKey = (userUpdate?: UserUpdate,) => {
    return [
    'PATCH', `/users/me`, userUpdate
    ] as const;
    }


export const getUpdateCurrentUserUsersMePatchQueryOptions = <TData = Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError = HTTPValidationError>(userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateCurrentUserUsersMePatchQueryKey(userUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>> = ({ signal }) => updateCurrentUserUsersMePatch(userUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateCurrentUserUsersMePatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>>
export type UpdateCurrentUserUsersMePatchQueryError = HTTPValidationError


export function useUpdateCurrentUserUsersMePatch<TData = Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError = HTTPValidationError>(
 userUpdate: UserUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>,
          TError,
          Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateCurrentUserUsersMePatch<TData = Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError = HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>,
          TError,
          Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateCurrentUserUsersMePatch<TData = Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError = HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Current User
 */

export function useUpdateCurrentUserUsersMePatch<TData = Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError = HTTPValidationError>(
 userUpdate: UserUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateCurrentUserUsersMePatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateCurrentUserUsersMePatchQueryOptions(userUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getCurrentUserOverviewUsersMeOverviewGetResponse200 = {
  data: UserOverviewResponse
  status: 200
}

export type getCurrentUserOverviewUsersMeOverviewGetResponseSuccess = (getCurrentUserOverviewUsersMeOverviewGetResponse200) & {
  headers: Headers;
};
;

export type getCurrentUserOverviewUsersMeOverviewGetResponse = (getCurrentUserOverviewUsersMeOverviewGetResponseSuccess)

export const getGetCurrentUserOverviewUsersMeOverviewGetUrl = () => {




  return `/users/me/overview`
}

/**
 * @summary Get Current User Overview
 */
export const getCurrentUserOverviewUsersMeOverviewGet = async ( options?: RequestInit): Promise<getCurrentUserOverviewUsersMeOverviewGetResponse> => {

  return apiMutator<getCurrentUserOverviewUsersMeOverviewGetResponse>(getGetCurrentUserOverviewUsersMeOverviewGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetCurrentUserOverviewUsersMeOverviewGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>, TError,void, TContext> => {

const mutationKey = ['getCurrentUserOverviewUsersMeOverviewGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>, void> = () => {


          return  getCurrentUserOverviewUsersMeOverviewGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCurrentUserOverviewUsersMeOverviewGetMutationResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>>

    export type GetCurrentUserOverviewUsersMeOverviewGetMutationError = unknown

    /**
 * @summary Get Current User Overview
 */
export const useGetCurrentUserOverviewUsersMeOverviewGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCurrentUserOverviewUsersMeOverviewGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetCurrentUserOverviewUsersMeOverviewGetMutationOptions(options), queryClient);
    }
    export type getCurrentUserProfileUsersMeProfileGetResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type getCurrentUserProfileUsersMeProfileGetResponseSuccess = (getCurrentUserProfileUsersMeProfileGetResponse200) & {
  headers: Headers;
};
;

export type getCurrentUserProfileUsersMeProfileGetResponse = (getCurrentUserProfileUsersMeProfileGetResponseSuccess)

export const getGetCurrentUserProfileUsersMeProfileGetUrl = () => {




  return `/users/me/profile`
}

/**
 * @summary Get Current User Profile
 */
export const getCurrentUserProfileUsersMeProfileGet = async ( options?: RequestInit): Promise<getCurrentUserProfileUsersMeProfileGetResponse> => {

  return apiMutator<getCurrentUserProfileUsersMeProfileGetResponse>(getGetCurrentUserProfileUsersMeProfileGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetCurrentUserProfileUsersMeProfileGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>, TError,void, TContext> => {

const mutationKey = ['getCurrentUserProfileUsersMeProfileGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>, void> = () => {


          return  getCurrentUserProfileUsersMeProfileGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCurrentUserProfileUsersMeProfileGetMutationResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>>

    export type GetCurrentUserProfileUsersMeProfileGetMutationError = unknown

    /**
 * @summary Get Current User Profile
 */
export const useGetCurrentUserProfileUsersMeProfileGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCurrentUserProfileUsersMeProfileGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getGetCurrentUserProfileUsersMeProfileGetMutationOptions(options), queryClient);
    }
    export type upsertCurrentUserProfileUsersMeProfilePutResponse200 = {
  data: UserProfileResponse
  status: 200
}

export type upsertCurrentUserProfileUsersMeProfilePutResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type upsertCurrentUserProfileUsersMeProfilePutResponseSuccess = (upsertCurrentUserProfileUsersMeProfilePutResponse200) & {
  headers: Headers;
};
export type upsertCurrentUserProfileUsersMeProfilePutResponseError = (upsertCurrentUserProfileUsersMeProfilePutResponse422) & {
  headers: Headers;
};

export type upsertCurrentUserProfileUsersMeProfilePutResponse = (upsertCurrentUserProfileUsersMeProfilePutResponseSuccess | upsertCurrentUserProfileUsersMeProfilePutResponseError)

export const getUpsertCurrentUserProfileUsersMeProfilePutUrl = () => {




  return `/users/me/profile`
}

/**
 * @summary Upsert Current User Profile
 */
export const upsertCurrentUserProfileUsersMeProfilePut = async (userProfileUpdate: UserProfileUpdate, options?: RequestInit): Promise<upsertCurrentUserProfileUsersMeProfilePutResponse> => {

  return apiMutator<upsertCurrentUserProfileUsersMeProfilePutResponse>(getUpsertCurrentUserProfileUsersMeProfilePutUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userProfileUpdate)
  }
);}





export const getUpsertCurrentUserProfileUsersMeProfilePutQueryKey = (userProfileUpdate?: UserProfileUpdate,) => {
    return [
    'PUT', `/users/me/profile`, userProfileUpdate
    ] as const;
    }


export const getUpsertCurrentUserProfileUsersMeProfilePutQueryOptions = <TData = Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError = HTTPValidationError>(userProfileUpdate: UserProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpsertCurrentUserProfileUsersMeProfilePutQueryKey(userProfileUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>> = ({ signal }) => upsertCurrentUserProfileUsersMeProfilePut(userProfileUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpsertCurrentUserProfileUsersMeProfilePutQueryResult = NonNullable<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>>
export type UpsertCurrentUserProfileUsersMeProfilePutQueryError = HTTPValidationError


export function useUpsertCurrentUserProfileUsersMeProfilePut<TData = Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError = HTTPValidationError>(
 userProfileUpdate: UserProfileUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>,
          TError,
          Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpsertCurrentUserProfileUsersMeProfilePut<TData = Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError = HTTPValidationError>(
 userProfileUpdate: UserProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>,
          TError,
          Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpsertCurrentUserProfileUsersMeProfilePut<TData = Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError = HTTPValidationError>(
 userProfileUpdate: UserProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Upsert Current User Profile
 */

export function useUpsertCurrentUserProfileUsersMeProfilePut<TData = Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError = HTTPValidationError>(
 userProfileUpdate: UserProfileUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof upsertCurrentUserProfileUsersMeProfilePut>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpsertCurrentUserProfileUsersMeProfilePutQueryOptions(userProfileUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type listBodyWeightLogsUsersMeBodyWeightLogsGetResponse200 = {
  data: BodyWeightLogResponse[]
  status: 200
}

export type listBodyWeightLogsUsersMeBodyWeightLogsGetResponseSuccess = (listBodyWeightLogsUsersMeBodyWeightLogsGetResponse200) & {
  headers: Headers;
};
;

export type listBodyWeightLogsUsersMeBodyWeightLogsGetResponse = (listBodyWeightLogsUsersMeBodyWeightLogsGetResponseSuccess)

export const getListBodyWeightLogsUsersMeBodyWeightLogsGetUrl = () => {




  return `/users/me/body-weight-logs`
}

/**
 * @summary List Body Weight Logs
 */
export const listBodyWeightLogsUsersMeBodyWeightLogsGet = async ( options?: RequestInit): Promise<listBodyWeightLogsUsersMeBodyWeightLogsGetResponse> => {

  return apiMutator<listBodyWeightLogsUsersMeBodyWeightLogsGetResponse>(getListBodyWeightLogsUsersMeBodyWeightLogsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}




export const getListBodyWeightLogsUsersMeBodyWeightLogsGetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>, TError,void, TContext> => {

const mutationKey = ['listBodyWeightLogsUsersMeBodyWeightLogsGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>, void> = () => {


          return  listBodyWeightLogsUsersMeBodyWeightLogsGet(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ListBodyWeightLogsUsersMeBodyWeightLogsGetMutationResult = NonNullable<Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>>

    export type ListBodyWeightLogsUsersMeBodyWeightLogsGetMutationError = unknown

    /**
 * @summary List Body Weight Logs
 */
export const useListBodyWeightLogsUsersMeBodyWeightLogsGet = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>, TError,void, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof listBodyWeightLogsUsersMeBodyWeightLogsGet>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getListBodyWeightLogsUsersMeBodyWeightLogsGetMutationOptions(options), queryClient);
    }
    export type createBodyWeightLogUsersMeBodyWeightLogsPostResponse201 = {
  data: BodyWeightLogResponse
  status: 201
}

export type createBodyWeightLogUsersMeBodyWeightLogsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createBodyWeightLogUsersMeBodyWeightLogsPostResponseSuccess = (createBodyWeightLogUsersMeBodyWeightLogsPostResponse201) & {
  headers: Headers;
};
export type createBodyWeightLogUsersMeBodyWeightLogsPostResponseError = (createBodyWeightLogUsersMeBodyWeightLogsPostResponse422) & {
  headers: Headers;
};

export type createBodyWeightLogUsersMeBodyWeightLogsPostResponse = (createBodyWeightLogUsersMeBodyWeightLogsPostResponseSuccess | createBodyWeightLogUsersMeBodyWeightLogsPostResponseError)

export const getCreateBodyWeightLogUsersMeBodyWeightLogsPostUrl = () => {




  return `/users/me/body-weight-logs`
}

/**
 * @summary Create Body Weight Log
 */
export const createBodyWeightLogUsersMeBodyWeightLogsPost = async (bodyWeightLogCreate: BodyWeightLogCreate, options?: RequestInit): Promise<createBodyWeightLogUsersMeBodyWeightLogsPostResponse> => {

  return apiMutator<createBodyWeightLogUsersMeBodyWeightLogsPostResponse>(getCreateBodyWeightLogUsersMeBodyWeightLogsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(bodyWeightLogCreate)
  }
);}





export const getCreateBodyWeightLogUsersMeBodyWeightLogsPostQueryKey = (bodyWeightLogCreate?: BodyWeightLogCreate,) => {
    return [
    'POST', `/users/me/body-weight-logs`, bodyWeightLogCreate
    ] as const;
    }


export const getCreateBodyWeightLogUsersMeBodyWeightLogsPostQueryOptions = <TData = Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError = HTTPValidationError>(bodyWeightLogCreate: BodyWeightLogCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreateBodyWeightLogUsersMeBodyWeightLogsPostQueryKey(bodyWeightLogCreate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>> = ({ signal }) => createBodyWeightLogUsersMeBodyWeightLogsPost(bodyWeightLogCreate, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreateBodyWeightLogUsersMeBodyWeightLogsPostQueryResult = NonNullable<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>>
export type CreateBodyWeightLogUsersMeBodyWeightLogsPostQueryError = HTTPValidationError


export function useCreateBodyWeightLogUsersMeBodyWeightLogsPost<TData = Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError = HTTPValidationError>(
 bodyWeightLogCreate: BodyWeightLogCreate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>,
          TError,
          Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateBodyWeightLogUsersMeBodyWeightLogsPost<TData = Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError = HTTPValidationError>(
 bodyWeightLogCreate: BodyWeightLogCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>,
          TError,
          Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreateBodyWeightLogUsersMeBodyWeightLogsPost<TData = Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError = HTTPValidationError>(
 bodyWeightLogCreate: BodyWeightLogCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Body Weight Log
 */

export function useCreateBodyWeightLogUsersMeBodyWeightLogsPost<TData = Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError = HTTPValidationError>(
 bodyWeightLogCreate: BodyWeightLogCreate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof createBodyWeightLogUsersMeBodyWeightLogsPost>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreateBodyWeightLogUsersMeBodyWeightLogsPostQueryOptions(bodyWeightLogCreate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse200 = {
  data: BodyWeightLogResponse
  status: 200
}

export type getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponseSuccess = (getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse200) & {
  headers: Headers;
};
export type getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponseError = (getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse422) & {
  headers: Headers;
};

export type getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse = (getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponseSuccess | getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponseError)

export const getGetBodyWeightLogUsersMeBodyWeightLogsLogIdGetUrl = (logId: number,) => {




  return `/users/me/body-weight-logs/${logId}`
}

/**
 * @summary Get Body Weight Log
 */
export const getBodyWeightLogUsersMeBodyWeightLogsLogIdGet = async (logId: number, options?: RequestInit): Promise<getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse> => {

  return apiMutator<getBodyWeightLogUsersMeBodyWeightLogsLogIdGetResponse>(getGetBodyWeightLogUsersMeBodyWeightLogsLogIdGetUrl(logId),
  {
    ...options,
    method: 'GET'


  }
);}




export const getGetBodyWeightLogUsersMeBodyWeightLogsLogIdGetMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>, TError,{logId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>, TError,{logId: number}, TContext> => {

const mutationKey = ['getBodyWeightLogUsersMeBodyWeightLogsLogIdGet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>, {logId: number}> = (props) => {
          const {logId} = props ?? {};

          return  getBodyWeightLogUsersMeBodyWeightLogsLogIdGet(logId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetBodyWeightLogUsersMeBodyWeightLogsLogIdGetMutationResult = NonNullable<Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>>

    export type GetBodyWeightLogUsersMeBodyWeightLogsLogIdGetMutationError = HTTPValidationError

    /**
 * @summary Get Body Weight Log
 */
export const useGetBodyWeightLogUsersMeBodyWeightLogsLogIdGet = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>, TError,{logId: number}, TContext>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getBodyWeightLogUsersMeBodyWeightLogsLogIdGet>>,
        TError,
        {logId: number},
        TContext
      > => {
      return useMutation(getGetBodyWeightLogUsersMeBodyWeightLogsLogIdGetMutationOptions(options), queryClient);
    }
    export type updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse200 = {
  data: BodyWeightLogResponse
  status: 200
}

export type updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponseSuccess = (updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse200) & {
  headers: Headers;
};
export type updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponseError = (updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse422) & {
  headers: Headers;
};

export type updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse = (updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponseSuccess | updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponseError)

export const getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchUrl = (logId: number,) => {




  return `/users/me/body-weight-logs/${logId}`
}

/**
 * @summary Update Body Weight Log
 */
export const updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch = async (logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options?: RequestInit): Promise<updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse> => {

  return apiMutator<updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchResponse>(getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchUrl(logId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(bodyWeightLogUpdate)
  }
);}





export const getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryKey = (logId: number,
    bodyWeightLogUpdate?: BodyWeightLogUpdate,) => {
    return [
    'PATCH', `/users/me/body-weight-logs/${logId}`, bodyWeightLogUpdate
    ] as const;
    }


export const getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryOptions = <TData = Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError = HTTPValidationError>(logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryKey(logId,bodyWeightLogUpdate);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>> = ({ signal }) => updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch(logId,bodyWeightLogUpdate, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: logId !== null && logId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryResult = NonNullable<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>>
export type UpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryError = HTTPValidationError


export function useUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch<TData = Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError = HTTPValidationError>(
 logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch<TData = Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError = HTTPValidationError>(
 logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>,
          TError,
          Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch<TData = Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError = HTTPValidationError>(
 logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Body Weight Log
 */

export function useUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch<TData = Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError = HTTPValidationError>(
 logId: number,
    bodyWeightLogUpdate: BodyWeightLogUpdate, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof updateBodyWeightLogUsersMeBodyWeightLogsLogIdPatch>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUpdateBodyWeightLogUsersMeBodyWeightLogsLogIdPatchQueryOptions(logId,bodyWeightLogUpdate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponseSuccess = (deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponseError = (deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse = (deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponseSuccess | deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponseError)

export const getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteUrl = (logId: number,) => {




  return `/users/me/body-weight-logs/${logId}`
}

/**
 * @summary Delete Body Weight Log
 */
export const deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete = async (logId: number, options?: RequestInit): Promise<deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse> => {

  return apiMutator<deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteResponse>(getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteUrl(logId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryKey = (logId: number,) => {
    return [
    'DELETE', `/users/me/body-weight-logs/${logId}`
    ] as const;
    }


export const getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryOptions = <TData = Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError = HTTPValidationError>(logId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryKey(logId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>> = ({ signal }) => deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete(logId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: logId !== null && logId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryResult = NonNullable<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>>
export type DeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryError = HTTPValidationError


export function useDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete<TData = Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError = HTTPValidationError>(
 logId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete<TData = Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError = HTTPValidationError>(
 logId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>,
          TError,
          Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete<TData = Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError = HTTPValidationError>(
 logId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Body Weight Log
 */

export function useDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete<TData = Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError = HTTPValidationError>(
 logId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteBodyWeightLogUsersMeBodyWeightLogsLogIdDelete>>, TError, TData>>, request?: SecondParameter<typeof apiMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteBodyWeightLogUsersMeBodyWeightLogsLogIdDeleteQueryOptions(logId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






