/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  AuthResponse,
  HTTPValidationError,
  LoginRequest,
  RefreshTokenRequest,
  RegisterRequest,
  UserResponse
} from '../../model';


export type registerUserAuthRegisterPostResponse201 = {
  data: AuthResponse
  status: 201
}

export type registerUserAuthRegisterPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type registerUserAuthRegisterPostResponseSuccess = (registerUserAuthRegisterPostResponse201) & {
  headers: Headers;
};
export type registerUserAuthRegisterPostResponseError = (registerUserAuthRegisterPostResponse422) & {
  headers: Headers;
};

export type registerUserAuthRegisterPostResponse = (registerUserAuthRegisterPostResponseSuccess | registerUserAuthRegisterPostResponseError)

export const getRegisterUserAuthRegisterPostUrl = () => {




  return `/auth/register`
}

/**
 * @summary Register User
 */
export const registerUserAuthRegisterPost = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<registerUserAuthRegisterPostResponse> => {

  const res = await fetch(getRegisterUserAuthRegisterPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerUserAuthRegisterPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerUserAuthRegisterPostResponse
}


export type loginUserAuthLoginPostResponse200 = {
  data: AuthResponse
  status: 200
}

export type loginUserAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginUserAuthLoginPostResponseSuccess = (loginUserAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginUserAuthLoginPostResponseError = (loginUserAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginUserAuthLoginPostResponse = (loginUserAuthLoginPostResponseSuccess | loginUserAuthLoginPostResponseError)

export const getLoginUserAuthLoginPostUrl = () => {




  return `/auth/login`
}

/**
 * @summary Login User
 */
export const loginUserAuthLoginPost = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginUserAuthLoginPostResponse> => {

  const res = await fetch(getLoginUserAuthLoginPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginUserAuthLoginPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginUserAuthLoginPostResponse
}


export type refreshTokensAuthRefreshPostResponse200 = {
  data: AuthResponse
  status: 200
}

export type refreshTokensAuthRefreshPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type refreshTokensAuthRefreshPostResponseSuccess = (refreshTokensAuthRefreshPostResponse200) & {
  headers: Headers;
};
export type refreshTokensAuthRefreshPostResponseError = (refreshTokensAuthRefreshPostResponse422) & {
  headers: Headers;
};

export type refreshTokensAuthRefreshPostResponse = (refreshTokensAuthRefreshPostResponseSuccess | refreshTokensAuthRefreshPostResponseError)

export const getRefreshTokensAuthRefreshPostUrl = () => {




  return `/auth/refresh`
}

/**
 * @summary Refresh Tokens
 */
export const refreshTokensAuthRefreshPost = async (refreshTokenRequest: RefreshTokenRequest, options?: RequestInit): Promise<refreshTokensAuthRefreshPostResponse> => {

  const res = await fetch(getRefreshTokensAuthRefreshPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(refreshTokenRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: refreshTokensAuthRefreshPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshTokensAuthRefreshPostResponse
}


export type getMeAuthMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getMeAuthMeGetResponseSuccess = (getMeAuthMeGetResponse200) & {
  headers: Headers;
};
;

export type getMeAuthMeGetResponse = (getMeAuthMeGetResponseSuccess)

export const getGetMeAuthMeGetUrl = () => {




  return `/auth/me`
}

/**
 * @summary Get Me
 */
export const getMeAuthMeGet = async ( options?: RequestInit): Promise<getMeAuthMeGetResponse> => {

  const res = await fetch(getGetMeAuthMeGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMeAuthMeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMeAuthMeGetResponse
}


