/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Athelix_API
 * Backend API for workout tracking, exercise logging, personal record detection, mesocycle planning, and training analytics.
 * OpenAPI spec version: 0.1.0
 */
import type {
  ExerciseSetCreate,
  ExerciseSetResponse,
  ExerciseSetUpdate,
  HTTPValidationError,
  WorkoutSessionCreate,
  WorkoutSessionDetailResponse,
  WorkoutSessionResponse,
  WorkoutSessionUpdate
} from '../../model';


export type listWorkoutSessionsWorkoutSessionsGetResponse200 = {
  data: WorkoutSessionResponse[]
  status: 200
}

export type listWorkoutSessionsWorkoutSessionsGetResponseSuccess = (listWorkoutSessionsWorkoutSessionsGetResponse200) & {
  headers: Headers;
};
;

export type listWorkoutSessionsWorkoutSessionsGetResponse = (listWorkoutSessionsWorkoutSessionsGetResponseSuccess)

export const getListWorkoutSessionsWorkoutSessionsGetUrl = () => {




  return `/workout-sessions`
}

/**
 * @summary List Workout Sessions
 */
export const listWorkoutSessionsWorkoutSessionsGet = async ( options?: RequestInit): Promise<listWorkoutSessionsWorkoutSessionsGetResponse> => {

  const res = await fetch(getListWorkoutSessionsWorkoutSessionsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listWorkoutSessionsWorkoutSessionsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listWorkoutSessionsWorkoutSessionsGetResponse
}


export type createWorkoutSessionWorkoutSessionsPostResponse201 = {
  data: WorkoutSessionResponse
  status: 201
}

export type createWorkoutSessionWorkoutSessionsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createWorkoutSessionWorkoutSessionsPostResponseSuccess = (createWorkoutSessionWorkoutSessionsPostResponse201) & {
  headers: Headers;
};
export type createWorkoutSessionWorkoutSessionsPostResponseError = (createWorkoutSessionWorkoutSessionsPostResponse422) & {
  headers: Headers;
};

export type createWorkoutSessionWorkoutSessionsPostResponse = (createWorkoutSessionWorkoutSessionsPostResponseSuccess | createWorkoutSessionWorkoutSessionsPostResponseError)

export const getCreateWorkoutSessionWorkoutSessionsPostUrl = () => {




  return `/workout-sessions`
}

/**
 * @summary Create Workout Session
 */
export const createWorkoutSessionWorkoutSessionsPost = async (workoutSessionCreate: WorkoutSessionCreate, options?: RequestInit): Promise<createWorkoutSessionWorkoutSessionsPostResponse> => {

  const res = await fetch(getCreateWorkoutSessionWorkoutSessionsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutSessionCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createWorkoutSessionWorkoutSessionsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createWorkoutSessionWorkoutSessionsPostResponse
}


export type getWorkoutSessionWorkoutSessionsSessionIdGetResponse200 = {
  data: WorkoutSessionDetailResponse
  status: 200
}

export type getWorkoutSessionWorkoutSessionsSessionIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getWorkoutSessionWorkoutSessionsSessionIdGetResponseSuccess = (getWorkoutSessionWorkoutSessionsSessionIdGetResponse200) & {
  headers: Headers;
};
export type getWorkoutSessionWorkoutSessionsSessionIdGetResponseError = (getWorkoutSessionWorkoutSessionsSessionIdGetResponse422) & {
  headers: Headers;
};

export type getWorkoutSessionWorkoutSessionsSessionIdGetResponse = (getWorkoutSessionWorkoutSessionsSessionIdGetResponseSuccess | getWorkoutSessionWorkoutSessionsSessionIdGetResponseError)

export const getGetWorkoutSessionWorkoutSessionsSessionIdGetUrl = (sessionId: number,) => {




  return `/workout-sessions/${sessionId}`
}

/**
 * @summary Get Workout Session
 */
export const getWorkoutSessionWorkoutSessionsSessionIdGet = async (sessionId: number, options?: RequestInit): Promise<getWorkoutSessionWorkoutSessionsSessionIdGetResponse> => {

  const res = await fetch(getGetWorkoutSessionWorkoutSessionsSessionIdGetUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getWorkoutSessionWorkoutSessionsSessionIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getWorkoutSessionWorkoutSessionsSessionIdGetResponse
}


export type updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse200 = {
  data: WorkoutSessionResponse
  status: 200
}

export type updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateWorkoutSessionWorkoutSessionsSessionIdPatchResponseSuccess = (updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse200) & {
  headers: Headers;
};
export type updateWorkoutSessionWorkoutSessionsSessionIdPatchResponseError = (updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse422) & {
  headers: Headers;
};

export type updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse = (updateWorkoutSessionWorkoutSessionsSessionIdPatchResponseSuccess | updateWorkoutSessionWorkoutSessionsSessionIdPatchResponseError)

export const getUpdateWorkoutSessionWorkoutSessionsSessionIdPatchUrl = (sessionId: number,) => {




  return `/workout-sessions/${sessionId}`
}

/**
 * @summary Update Workout Session
 */
export const updateWorkoutSessionWorkoutSessionsSessionIdPatch = async (sessionId: number,
    workoutSessionUpdate: WorkoutSessionUpdate, options?: RequestInit): Promise<updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse> => {

  const res = await fetch(getUpdateWorkoutSessionWorkoutSessionsSessionIdPatchUrl(sessionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(workoutSessionUpdate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateWorkoutSessionWorkoutSessionsSessionIdPatchResponse
}


export type deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponseSuccess = (deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponseError = (deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse = (deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponseSuccess | deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponseError)

export const getDeleteWorkoutSessionWorkoutSessionsSessionIdDeleteUrl = (sessionId: number,) => {




  return `/workout-sessions/${sessionId}`
}

/**
 * @summary Delete Workout Session
 */
export const deleteWorkoutSessionWorkoutSessionsSessionIdDelete = async (sessionId: number, options?: RequestInit): Promise<deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse> => {

  const res = await fetch(getDeleteWorkoutSessionWorkoutSessionsSessionIdDeleteUrl(sessionId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteWorkoutSessionWorkoutSessionsSessionIdDeleteResponse
}


export type listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse200 = {
  data: ExerciseSetResponse[]
  status: 200
}

export type listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listExerciseSetsWorkoutSessionsSessionIdSetsGetResponseSuccess = (listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse200) & {
  headers: Headers;
};
export type listExerciseSetsWorkoutSessionsSessionIdSetsGetResponseError = (listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse422) & {
  headers: Headers;
};

export type listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse = (listExerciseSetsWorkoutSessionsSessionIdSetsGetResponseSuccess | listExerciseSetsWorkoutSessionsSessionIdSetsGetResponseError)

export const getListExerciseSetsWorkoutSessionsSessionIdSetsGetUrl = (sessionId: number,) => {




  return `/workout-sessions/${sessionId}/sets`
}

/**
 * @summary List Exercise Sets
 */
export const listExerciseSetsWorkoutSessionsSessionIdSetsGet = async (sessionId: number, options?: RequestInit): Promise<listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse> => {

  const res = await fetch(getListExerciseSetsWorkoutSessionsSessionIdSetsGetUrl(sessionId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listExerciseSetsWorkoutSessionsSessionIdSetsGetResponse
}


export type createExerciseSetWorkoutSessionsSessionIdSetsPostResponse201 = {
  data: ExerciseSetResponse
  status: 201
}

export type createExerciseSetWorkoutSessionsSessionIdSetsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createExerciseSetWorkoutSessionsSessionIdSetsPostResponseSuccess = (createExerciseSetWorkoutSessionsSessionIdSetsPostResponse201) & {
  headers: Headers;
};
export type createExerciseSetWorkoutSessionsSessionIdSetsPostResponseError = (createExerciseSetWorkoutSessionsSessionIdSetsPostResponse422) & {
  headers: Headers;
};

export type createExerciseSetWorkoutSessionsSessionIdSetsPostResponse = (createExerciseSetWorkoutSessionsSessionIdSetsPostResponseSuccess | createExerciseSetWorkoutSessionsSessionIdSetsPostResponseError)

export const getCreateExerciseSetWorkoutSessionsSessionIdSetsPostUrl = (sessionId: number,) => {




  return `/workout-sessions/${sessionId}/sets`
}

/**
 * @summary Create Exercise Set
 */
export const createExerciseSetWorkoutSessionsSessionIdSetsPost = async (sessionId: number,
    exerciseSetCreate: ExerciseSetCreate, options?: RequestInit): Promise<createExerciseSetWorkoutSessionsSessionIdSetsPostResponse> => {

  const res = await fetch(getCreateExerciseSetWorkoutSessionsSessionIdSetsPostUrl(sessionId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exerciseSetCreate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createExerciseSetWorkoutSessionsSessionIdSetsPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createExerciseSetWorkoutSessionsSessionIdSetsPostResponse
}


export type getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse200 = {
  data: ExerciseSetResponse
  status: 200
}

export type getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponseSuccess = (getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse200) & {
  headers: Headers;
};
export type getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponseError = (getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse422) & {
  headers: Headers;
};

export type getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse = (getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponseSuccess | getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponseError)

export const getGetExerciseSetWorkoutSessionsSessionIdSetsSetIdGetUrl = (sessionId: number,
    setId: number,) => {




  return `/workout-sessions/${sessionId}/sets/${setId}`
}

/**
 * @summary Get Exercise Set
 */
export const getExerciseSetWorkoutSessionsSessionIdSetsSetIdGet = async (sessionId: number,
    setId: number, options?: RequestInit): Promise<getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse> => {

  const res = await fetch(getGetExerciseSetWorkoutSessionsSessionIdSetsSetIdGetUrl(sessionId,setId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getExerciseSetWorkoutSessionsSessionIdSetsSetIdGetResponse
}


export type updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse200 = {
  data: ExerciseSetResponse
  status: 200
}

export type updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponseSuccess = (updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse200) & {
  headers: Headers;
};
export type updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponseError = (updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse422) & {
  headers: Headers;
};

export type updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse = (updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponseSuccess | updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponseError)

export const getUpdateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchUrl = (sessionId: number,
    setId: number,) => {




  return `/workout-sessions/${sessionId}/sets/${setId}`
}

/**
 * @summary Update Exercise Set
 */
export const updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatch = async (sessionId: number,
    setId: number,
    exerciseSetUpdate: ExerciseSetUpdate, options?: RequestInit): Promise<updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse> => {

  const res = await fetch(getUpdateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchUrl(sessionId,setId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(exerciseSetUpdate)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateExerciseSetWorkoutSessionsSessionIdSetsSetIdPatchResponse
}


export type deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponseSuccess = (deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponseError = (deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse = (deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponseSuccess | deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponseError)

export const getDeleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteUrl = (sessionId: number,
    setId: number,) => {




  return `/workout-sessions/${sessionId}/sets/${setId}`
}

/**
 * @summary Delete Exercise Set
 */
export const deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDelete = async (sessionId: number,
    setId: number, options?: RequestInit): Promise<deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse> => {

  const res = await fetch(getDeleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteUrl(sessionId,setId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteExerciseSetWorkoutSessionsSessionIdSetsSetIdDeleteResponse
}


